<h1>Hotel booking conditions via GUARANT International</h1>

<h2>Cancellations, changes and refunds</h2> 

<p>Please inform GUARANT International about any amendments or cancellations in writing by fax: + 420 284 001 448 or e-mail: <a href="mailto:terena2011@guarant.cz">terena2011@guarant.cz</a>. Telephone amendments will not be accepted.</p> 

<p>Date of delivery of your written cancellation to the local conference organiser will be considered as the date of cancellation.</p> 

<p>Please do not contact the hotel directly for any reservation changes or cancellations. The appropriate refunds will be made after the conference.</p> 

<h2>Cancellation conditions</h2>

<p>The following cancellation conditions apply to the cancellation of a hotel reservation:<br /> 

<strong>Cancellation before and on April 12, 2011: full refund (less 15 EUR handling fee)<br />
Cancellation after April 12, 2011: one night cancellation fee<br />
No show: one night cancellation fee</strong></p>

<p>In case of a no show, the room will be kept for the guest until 12 noon of the day following the date of expected arrival; the room will then be released.</p>

<p>Change of the date of arrival is possible until 12 noon prior to the scheduled arrival date. In case the request of a change is received after 12 noon, a one-night cancellation fee will be charged.</p>

<h2>Terms of payment </h2> 

<p>For reservations after April 12, 2011: Please note that payment by bank transfer is possible until April 22, 2011.</p> 
<p>After this date only payments by credit cards will be accepted (you can either use the on-line payment system or send us an authorization form as mentioned below).</p> 

<p>Hotel accommodation must be paid in Euro by:</p> 

<p>Bank Transfer<br /> 
Bank name: 		Ceskoslovenska obchodni banka<br /> 
Bank address: 		Na Prikope 18, 110 00 Prague 1, Czech Republic<br /> 
Account name: 	GUARANT International spol s.r.o.<br /> 
Account number: 	478 533 893<br />
IBAN: 		CZ69 0300 0000 0004 7853 3893<br /> 
BIC/SWIFT code: 	CEKOCZPP<br /> 
Details of payment: 	TERENA 2011 / participants name</p> 


<p>The participant&rsquo;s name should be clearly legible otherwise the payment cannot be identified.</p> 

<p>All payments made by bank transfer have to be net of all bank charges. The payer pays the bank charges of their bank, and the beneficiary pays the charges of their bank, if any.</p> 

<p>To simplify the identification of your payment please enclose a copy of your bank transfer with the registration form and send it to the local conference organiser by fax: +420 284 001 448 or via e-mail: <a href="mailto:terena2011@guarant.cz">terena2011@guarant.cz</a>.</p>

<h2>Credit Cards</h2> 

<p>For payments through the On-line Payment System (available after login) only Mastercard/Eurocard and VISA credit cards are accepted. These payments will be charged in EUR.</p> 

<p>Please note, that payment through the On-line Payment System is available once the Letter of Confirmation is received.</p> 

<p>In case you would like to use other credit cards such as Diners Club or American Express, please note, that these would be charged in local currency K&#269;, Czech Crowns (CZK) at the exchange rate of the Czech National Bank on the date of payment.</p> 

<p>The approximate exchange rate is 1 EUR = 24, 449 CZK (January 2011).</p>  

<p>For payment using Diners Club or American Express Card please complete <a href="/includes/tnc2011/documents/authorization_form.doc" title="authorization form">Credit Card Payment Authorization Form</a> and kindly send it signed by a card holder to Conference Secretariat by fax: + 420 284 001 448 or scanned copy via e-mail: <a href="mailto:terena2011@guarant.cz">terena2011@guarant.cz</a>.</p>
