	<? /*<div class="widebox">
			<div class="body">
	<h1>Map Clarion Congress Hotel Prague</h1>
     <p><img alt="Map Clarion" src="/includes/tnc2011/gfx/photos/clarionfloormap.png"/></p>
      <div class="clearer"></div>
   </div>
        <div class="closer"></div>
      </div><!--end widebox-->*/ ?>

   <div class="widebox">
		  	<div class="body">
        <div class="legend">
	        <h1>TNC2012 Area Map</h1>
          <h1 class="legend">Legend</h1>
          <ul class="legend">
            <li id="gm_venue">Venue</li>
            <li id="gm_train">Transportation</li>
            <li id="gm_hotel">Hotels (tbc)</li>
          </ul>
          <? /*<h1 class="legend">Locations</h1>
          <ol>
            <li>Hotel 1</li>
            <li>Hotel 2</li>
            <li>Hotel 3</li>
            <li>Hotel 4</li>
            <li>Hotel 5</li>
            <li>Hotel 6</li>
            <li>Hotel 7</li>
            <li>Hotel 8</li>
            <li>Hotel 9</li>

          </ol>*/ ?>

        <div>
          <p>Click on the appropriate marker to display more detailed information, pan and zoom using the controls top left.</p>
          <p>Find more detailed information about hotels above on this page.</p>
        </div>
		</div>
        <div id="map"></div>

        <div class="clearer"></div>

      	</div>
        <div class="closer"></div>
      </div><!--end widebox-->