    	<h1 class="lined">Welcome to Reykjavik, Iceland</h1>
      <p id="venuep">
      	Reykjavik is the capital of Iceland and the northenmost capital city in the world, it was founded in 1786. The Reykjavik Capital Area has just under 200,000 inhabitants, about 60% of the country's total population of 300,000.<br /><br />
      	
      	 Reykjavík is a young and daring city characterised by strong contrasts. Conveniently small, clean and safe, it is essentially free of the major problems that haunt most other capitals. Visitors to Reykjavik cannot escape experiencing the vibrant energy at the heart of Iceland’s capital city.  Whether you want to feel the boiling thermal energy underground, get close to the natural green energy within the city and around it, or experience its lively culture and funfilled nightlife, you should be in for a very memorable visit.<br /><br />
      	 For more information visit: <a href="http://www.visitreykjavik.is/">http://www.visitreykjavik.is/</a>
      	 </p>
    	<div class="bigbox">
				<div class="body">
          <h1>Photos of Iceland</h1>
		<?= $this->render('_shared/venue_pictures.phtml'); ?>
      	</div><!--end big box body-->
        <div class="closer"></div>
      </div><!--end big box-->
      <? /*
      <div class="bigbox">

        <div class="body">
          <h1>More about Bruges (Brugge)</h1>
          <h2>Bore feugiam ip er secte</h2>
          <p>Bore feugiam ip er secteBore feugiam ip er secte
          Ortie faccum zzrit lum eugait ad etue moloborerat velis nosto commy nonulla alis adignisl ullaorper augiamet am, summodolorem vulla acil utet ad tio consed ea
          feugait num non ute ming enim at.Il ute magnim zzrit ipsusci liquamc ommolor
          ationum quamet, sequisl utpat nonsequisi.</p>

          <p>Bore feugiam ip er sectet praesto odolor sustrud dolenissit alisi.
          Xercidunt lobore veniamet velit esto eugiam, conse feugait dolortisi.
          Rud tatetum zzrilit nos exerostie core facin velit landignis dio esto odolore
          delissendre molesenim incilis modigna feum iliquis sequat, senissit, quisim atummodolor sustin ex endigna faccum vel utat lor aliquis aut acilit euip eum vel dit, sectem quat nosto consectet, vulla ad ex euiscillut lor sit vel ex eugiam, sumsandre tincinc illandre tat at.</p>

          <h2>Sum zzril incillam</h2>
          <p>Im quat euguero core dit wissi.Quat inisi. Del elit nim incilis eumsan ero od mincilit ilit la feu feuisl eu faci blaor adipis nosto eu feuismo dipisim veliquat aliquip iscilla ad do odignim illa con et at aliquam dolummod exero odolore tat. In volor sectem nummodipsum nos et praese magnim nim nos nonsectem iriuscin veniam, corperaestis num quat wis autetum ing et at wisl diam veliscilit, quat utpationse dolute feum vent voloreetue tin euisci tat del ing et praessed deliqui eugue dolore er adio odolorem quisl dolobore facing erillam, sum zzril incillam, sumsandreet ex et wisim zzrilit wis nullam, veriurem zzrit ad magna aci tion el irit wis eros acinit la faccum vullam, sequipit er sustie modiat vel dolore modolobore te modions equat. Duis nonsequam, cor il dipsum vendre ming ercing esendre velenim ing et adion ut.</p>
      	</div> */ ?>
		
		<!-- end body  -->
        <div class="closer"></div>
      </div><!--end big box-->
     
    <!--end content-->

    <div id="sidebar">
    	<div class="box">
    	<?= $this->render('_shared/venue_vcard.phtml'); ?>
      	<div class="closer"></div>
	  	</div><!--end box-->
      <div class="box">
				<div class="body">
          <h1>Tourist information</h1>
<p>People intending to travel to Iceland should inquire with the Directorate of Immigration (<a href="http://www.utl.is/">http://www.utl.is/</a>) whether they need to obtain a visa prior to arrival. The processing time of Schengen visas is 10 working days so be sure to file an application in good time.<br />For more information contact: <a href="mailto:tnc2012@terena.org?subject=TNC2012%20visa">tnc2012@terena.org</a></p>

          <h2>Weather and Climate</h2>
          <p>The climate of Iceland's coast is subpolar oceanic. The warm North Atlantic Current ensures generally higher annual temperatures than in most places of similar latitude in the world. Regions in the world with similar climate include the Aleutian Islands, the Alaska Peninsula, and Tierra del Fuego, although these regions are closer to the equator. Despite its proximity to the Arctic, the island's coasts remain ice-free through the winter. Ice incursions are rare, the last having occurred on the north coast in 1969.<br /><br />

There are some variations in the climate between different parts of the island. Generally speaking, the south coast is warmer, wetter and windier than the north. The Central Highlands are the coldest part of the country. Low-lying inland areas in the north are the most arid. Snowfall in winter is more common in the north than the south.<br /><br />
Average temperature in May: 9.4 - 3.6 Celsius</p>
          <p><a href="http://www.weather.is/" title="Weather Iceland">Weather Iceland</a><br /></p>

          <h2>Meta Info</h2>
          <p>Time zone Iceland: GMT (UTC+0)</p> <p>The official currency used in Iceland is the Icelandic króna which has the international abbreviation ISK. 1 ISK ~ 0.006 EUR. Rates can be checked at <a href="http://www.xe.com" title="xe.com">the currency converter</a>.</p>
          <p>The official language is Icelandic.</p>
          <p>The power supply in Iceland is 220 - 240 volts 50 Hertz and plugs are European standard with two round pins.</p>
          <img alt="power supply in Iceland" src="/includes/tnc2011/gfx/photos/img_electricity.jpg" />
				</div><!--end body-->
        <div class="closer"></div>
      </div><!--end box-->
