<br />
<div id="container">
<? 
if ($this->session['session']) {
	$session = $this->session;
	$upcoming = false;
} else {
	$session = $this->session['upcoming'];
	$upcoming = true;
}

?>

<h3>
<? 
if ($upcoming) { 
	echo 'Next '; 
} else {
	echo 'Current ';
}
?>Session
<? 
$tz = new Zend_Date();
if ($upcoming) {   
	echo 'starts in '.$this->timeUntil(new Zend_Date($session['session']['tstart']));
} 
?>
</h3>
<h1><?= $session['session']['title'] ?></h1>

<!--<p><?= $session['session']['description'] ?></p>-->

<ul class="basic">
<? foreach ($session['presentations'] as $presentation): ?>
<li><?= $presentation['title'] ?></li>
<? endforeach; ?>
</ul>
<br />


<table id="sessionspeakers">
<tr class="speakerrow_0 active" >
<? 
$i=0;
foreach ($session['speakers'] as $speaker): 
$i++; 
?>
<td>
<span><?= $speaker['fname'] ." ". $speaker['lname'] ?></span>
<? if ($speaker['file_id']): ?>

<div style="border: 1px solid black;
            border-radius: 10px;
            -moz-border-radius: 10px;
            -khtml-border-radius: 10px;
            -webkit-border-radius: 10px;
            width: 260px;
            height: 170px;
            background:url(/core/file/<?= $speaker['file_id'] ?>)">

<? else: ?>
<div>
<img src="/includes/core/gfx/no_image.gif" />
<? endif; ?>
</div>
</td>
<? if ( (count($session['speakers']) > 3) && ($i % 3 == 0) ): ?></tr><tr class="speakerrow_<?= $i/3 ?>" style="display:none;"><? endif; ?>
<? endforeach; ?>
</tr>
</table>
<br />
</div>