<p>Dear <?= $this->values['fname'] . ' ' . $this->values['lname'] ?>,</p>

<p>You are receiving this email because you are a member of <?= $this->conferenceInfo('name') ?> Programme Committee.</p>
<p>In order for you to review submitted papers, you need to have a new CORE account, our online COnference REgistration tool.</p>
<p>You will receive a separate e-mail later when we have assigned the papers to you.</p>
<p>Please take a moment to read the following instructions carefully - they
are not difficult, but there is only one opportunity to get it right as
your account is automatically created the first time you log in.
</p>

<?= $this->render('user/login_instructions.phtml') ?>
<?= $this->render('user/signature.phtml') ?>
