<blockquote><div>
This conference website is managed by CORE, a tool to manage multiple multilingual conference websites at the same time. (with their own look and feel) It's simple,
federated and open source. CORE is developed by <a href="mailto:gijtenbeek@terena.org">Christian Gijtenbeek</a> of TERENA.
</div>
</blockquote>

<h2>CORE Demo</h2>
<div id="coredemo_container">&nbsp;</div>

<h2>Federated</h2>
<p>
CORE allows you to login using your own institutional credentials, instead of having to remember another password, you now just have to remember one!
Depending on your given CORE role (set by the administrators of this website) certain features will be available to you on the tabs above.
This can range from a full admin, to a read only account.
</p>

<h2>Keep up to date</h2>
<p>
At the heart of CORE is the Conference Schedule with its sessions and side events. We added some useful features to make sure you don't miss anything!</p>
<ul class="basic">
<li>
Subscribe to our public TNC calendar, which is automatically synced with the CORE Schedule. If a sessions' time or place changes, the Google Calendar will be updated. This way you will always have up to date information!
<br /><br /><strong>iCal clients</strong>: http://www.google.com/calendar/ical/tnc2012%40terena.org/public/basic.ics
<br /><strong>Google Calendar</strong>: tnc2012@terena.org

</li>
<li>
If you are using Google Calendar you can export sessions or events to your own calendar. Go to a session or event and simply click on 'Save to my Google Calendar'. This is very
valuable if you need directions to an outside venue. (The event location is stored as a Google maps link)
</li>
<li>
If you don't use calendar software, you can keep up to date by subscribing to sessions. You do this by clicking on the
<img src="includes/tnc2012/gfx/icons/star_off.gif" alt="star" /> next to a session. Now when this session changes, you will be notified by email.
The extra benefit of subscribing to sessions is that you can build your own Conference Schedule. Clicking on 'Toggle subscribed sessions' will
only display the sessions that you expressed an interest in.
</li>
</ul>

<h2>Open Source</h2>
<p><a href="http://code.google.com/p/terena-core/">CORE is released under a BSD license</a>. CORE is setup as generically as possible, without many dependencies on a certain infrastructure. This means you
can get CORE up and running in no time. To encourage other developers to adapt and extend CORE, we have taken care to make the system as modular as possible. CORE is powered by Zend Framework and complies to PHP standard practices.
</p>
<h2>Simple</h2>
<p>This tool was born out of necessity for our own annual conference. We have always tried to make the user experience, for both end users and Conference admins alike, as pleasant as possible, so the focus is on simplicity. The code is also written with this in mind; less focus on features, more focus on an easy to use, and easily extendible codebase.
</p>
<h2>Problems?</h2>
<p>If you come across any issues, this is a new system after all, <a href="mailto:<?=$this->conferenceInfo('email') ?>">please let us know</a>. 
</p>
