<?= $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<?= $this->headTitle() ?>
<?= $this->headLink() ?>
<?= $this->headMeta() ?>
<?= $this->headStyle() ?>
<?= $this->headScript() ?>
<script type="text/javascript" src="/js/terena.js"></script>
<script type="text/javascript" src="/js/roomview.js"></script>
<meta http-equiv="Refresh" content="120;url=<?=Zend_Controller_Front::getInstance()->getRequest()->getRequestUri()?>"></meta>
<style type="text/css">
html, body {
	height:100%;
	margin:0;
	padding:0;
	font-size:16px;
}
#container {
	margin:0 auto;
	padding: 0 3em;
	border-radius: 10px; 
	-moz-border-radius: 10px; 
	-webkit-border-radius: 10px; 
}
#newsticker {
	position:fixed;
	bottom:0px;
	left:0px;
	padding:12px;
	margin:0;
	border-top:1px solid #C9C9C9;
	width:100%;
	font-size:14px;
	text-align:left;
}
body {
	background: url("/includes/tnc2012/gfx/layout/bg/body_tnc.jpg") no-repeat center center fixed #DDDDDD;
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	background-size: cover;
}
table {
	margin:0 !important;
}
table td {
	border:none;
	width:220px !important;
	padding:0;
	margin:0;
}
ul.basic li {
	color: #333333;
	font-size: 20px;
}
</style>
</head>
<body>
<?= $this->render('schedule/room.phtml') ?>
<div id="newsticker">
<span id="section">Announcements</span> | <span class="news_text"></span>
</div>
</body>
</html>