    	<div class="body">
    	
  <div class="vcard">
    <h1><abbr>TNC2012 Venue</abbr></h1>
    <h2><span class="fn org">Clarion Congress Hotel</span></h2>
    <div class="adr">
      <span class="street-address">Freyova 945/33</span><br />
      <span class="locality">Prague 9</span>,
      <span class="postal-code">19 000</span>
      <div class="country-name">Czech Republic</div>
    </div>
    <div class="tel">
      <abbr class="type" title="voice">T:</abbr>
      <span class="value">+420 211 131 116 </span>
               </div>
    <div class="em">Email:
      <span class="email"><a href="mailto:congress@cchp.cz">congress@cchp.cz</a></span>
    </div>
    <div>WWW:
      <a class="url" href="http://www.cchp.cz/en/home-page/ ">http://www.cchp.cz/</a>
    </div>
  </div>
</div>