<h1>Send <? if ($this->reminder): ?>reminder<? endif; ?> mail to reviewers [<?= $this->reviewers; ?>]</h1>
<?
$eventlogModel = new Core_Model_Eventlog();
$eventType = ($this->reminder) ? 'mail_reviewers-reminder' : 'mail_reviewers';
if ($mailout = $eventlogModel->getTimestampByType($eventType)): ?>
<p class="notice">
Last email run went out: <?=$this->timeSince($mailout->getTimestamp())?> ago, on <?=$this->formatDate($mailout)?>
</p>
<? endif; ?>
<? if (!empty($this->sent)): ?>
<? if ($this->dummy == 1): ?>
Testrun complete; The following emails were generated, please check them before sending (to send: 
<a href="<?= $this->url(array('controller' => 'review', 'action' => 'mail')) ?>">go back</a> and uncheck the 'test run' box).
<? else: ?>
Successfully mailed <?= $this->reviewers; ?> reviewers
<? endif; ?>

<ul>
<? foreach ($this->sent as $reviewer): ?>
<?
$name = $reviewer['email']. '_'. sha1($this->conferenceInfo('abbreviation').' Review') .'.eml'
?>
<li>
	<? if ($this->dummy == 1): ?>
	<? // dummy is set: make hyperlinks to generated emails so user can review them ?>
	<a href="/core/file/getstaticfile/file/<?= $name ?>/type/mail" title="download email">
	<?= $reviewer['email'] ?>
	</a>
	<? else: ?>
	<?= $reviewer['email'] ?>
	<? endif; ?>
</li>
<? endforeach; ?>
</ul>

<? else: ?>
<?
$template = $this->conferenceInfo('abbreviation') .'-reviewers.phtml';
?>
<p>
All users who have been assigned to review a submission will get an email with a list of submissions they should review.</p>
<p>
The emails will be generated using a combination of a static and a dynamic template. The static template is called
<code><?= $template ?></code> and can be found in <code>/application/modules/core/views/emails</code>.</p>
<?= $this->mailForm ?>
<? endif; ?>