<div id="streams" class="streams archive">
	<div id="str_details">
    	<h1 class="light">Video Archive<span id="activestream" style="display:none;"><?= $this->activeStream ?></span>		
    	<span id="quality" style="display:none;"><?= $this->quality ?></span></h1>
        <div id="accordion_archive">
			<? foreach($this->archive as $key => $item):
			$zd = new Zend_Date($key); ?>
            <h2 class="toggler atStart"><?= $this->formatDate($zd, null, 'EEEE') ?></h2>
            <ul class="element atStart archived">
				<? foreach ($item as $session): ?>
                <li>
	                <div class="newsmeta"></div>
	                <? $stream = $session->number.$session->location_abbreviation; ?>
	                <a href="<?= $this->url(array('controller'=>'media', 'action'=>'archive', 'stream'=>$stream), 'stream') ?>" title="Watch stream" class="rst_<?= $stream ?><? if ($this->activeStream == $stream): ?> active<? endif; ?>">
	                <?= htmlspecialchars($session->title) ?></a>
	                <div class="clearer"></div>
                </li>
				<? endforeach; ?>
            </ul>
			<? endforeach; ?>
		</div>
    </div><!--str_details-->
    <div id="mediacontent">
    	<form action="<?= $this->url() ?>" method="post" id="streamquality">
    	<div>
    	<label for="radio-lo"> low</label><input type="radio" value="lo" id="radio-lo" name="quality" <? if ($this->quality == 'lo'): ?>checked="checked" <? endif; ?> />
    	<label for="radio-hi"> high</label><input type="radio" value="hi" id="radio-hi" name="quality" <? if ($this->quality == 'hi'): ?>checked="checked" <? endif; ?> />
    	</div>
    	</form>    
    	<div id="mediacontent_container">
    		<p>Select a stream from the left. <a href="http://www.adobe.com/products/flashplayer/" title="download flash">Adobe Flash Player</a> is required to watch these streams.</p>
    	</div>
    </div><!--mediacontent-->
	<div class="clearer"></div>
</div>
<div class="clearer"></div>
<div class="bot_crnrs"></div>