<h1>Submit:</h1> 
<ul class="basic">
<!--<li>Presentation Abstract (25 minutes)</li>
<li>Full paper (When abstract is accepted)</li>
<li>Session proposal (90 minutes)</li>-->
<li>Lightning talk (5 minutes) - Indicate whether you would be willing to have your proposal considered as a lightning talk.</li>
<li>Poster - Indicate on your abstract whether you would be willing to have your proposal considered as a poster.</li>
</ul>
<? if ($this->error): ?>
<p class="notice">Something went wrong, please check!</p>
<? endif; ?>
<?= $this->submitForm ?>