This is an automated message.

Thank you for your paper (extended abstract) submission for the <?= $this->conferenceInfo('name') ?>.

The deadline for submission is 30 November.

At least two members of the Programme Committee will review your submission and the decision for acceptance will be made at the programme committee meeting in January 2012. By the end of that month, you will be advised of the committee's decision.

If you wish to submit an updated version of your paper, you are able to edit your originally submitted paper and you are kindly asked to append a version number (v2, v3, etc.).

Thank you for your interest in the conference. We look forward to seeing you in Reykjavik.

Sincerely,