<p><?= $this->conferenceInfo('name') ?>.</p></p>

<p>Dear <?= $this->values['fname'] ?> <?= $this->values['lname'] ?>,
</p>

<p>On behalf of the Programme Committee, it is my pleasure to inform you
that your submitted paper entitled "<?= $this->values['title'] ?>" has been
accepted for presentation at the <?= $this->conferenceInfo('name') ?>.</p>


<?
// prepare dates and times
$date = $this->formatDate($this->values['session']['tstart'], null, 'EEEE dd MMMM');
$time = $this->formatDate($this->values['session']['tstart'], null, 'HH:mm').'-'.
		$this->formatDate($this->values['session']['tend'], null, 'HH:mm');

?>

<p>
At present, you are scheduled to speak in a session on <?= $date ?>, from <?=$time?>.
<?
if ($chairs = $this->values['session']['chair']) {
	foreach ($chairs as $chair) {
		$chair = '<a href="mailto:'. $chair['email'] .'">'.$chair['fname']. ' '.$chair['lname'].'</a>';
	}
}
?>
<? if (isset($chair)): ?>Your session chair will be <?= $chair ?>. Please note that these details are subject to change.<? endif; ?>
<p>

<p>Comments from the programme committee:
<hr />
<ul>
<? foreach ($this->values['reviews'] as $review): ?>
<? if(!empty($review['comments_authors'])):?>
<li> <?= $review['comments_authors']?> </li>
<? endif; ?>
<? endforeach; ?>
</ul>
<hr />
<?#= $this->render($this->conferenceInfo('abbreviation').'-submit-accept.html.phtml') ?>
</p>


<p>
You will be hearing from us again very shortly with some information related to the event.</p>

<p>
Sincerely,<br /><br />

Gyöngyi Horváth<br />
Conference Organiser
</p>