This is an automated message.<br /><br />

Thank you for your paper (extended abstract) submission for the <?= $this->conferenceInfo('name') ?>.<br /><br />

To select the abstracts for presentation at the TNC2013, all submitted abstracts will go through three comprehensive reviews: (1) double-blind (at least two reviewers), (2) non-blind  and (3) participative peer reviews. Authors will receive the result of the evaluations by the reviewers of their abstracts at the end of January 2013.<br /><br />

If you wish to revise your submitted abstract you can do so until 30 November 2012 by going to <a href="<?= $this->url(array('controller'=>'user', 'action'=>'edit', 'user_id'=>$this->authInfo('user_id'))) ?>">'Edit Account'</a>
Your submitted abstracts are listed at the end of your profile and you are able to edit them by clicking on the titles.<br /><br />

If you have any questions concerning the conference system please contact:<br /> <a href="mailto:webmaster@terena.org">webmaster@terena.org</a><br />
Any other questions related to the conference should be addressed to:<br />
<a href="mailto:tnc2013@terena.org">tnc2013@terena.org</a><br /><br />

Thank you for your interest in the conference.<br />
We look forward to seeing you in Maastricht.<br /><br />

Sincerely,<br />
TNC2013 Admin Team