<?
$scope = $this;
$submission_types = array_map(function($val) use($scope) {
	return $scope->getFormValue('submission_type', $val, 'submit');
},$this->values['submission_type']);
?>
This is an automated message. Thank you for your submission of "<?= $this->values['title'] ?>", (<?= implode(', ',$submission_types) ?>) for the TNC15 Conference.
The decision for acceptance will be made at the programme committee meeting in January 2015. By the end of that month, you will be advised of the committee's decision. 

To edit your submission(s):


- visit https://tnc15.terena.org/
- click on Sign in
- click on Edit account
- scroll down to the bottom of the page and edit the paper(s) listed there
- please append a version number (v2, v3, etc.)


We look forward to seeing you in Porto. Sincerely,


TERENA TNC15

Singel 468 D
Amsterdam, 1017 AW
The Netherlands

T: +31 20 530 44 88
F: +31 20 530 44 99

Email: tnc15@terena.org
Url: http://tnc15.terena.org/


