This is an automated message.

Thank you for your paper (extended abstract) submission for the <?= $this->conferenceInfo('name') ?>.

To select the abstracts for presentation at the TNC2012, all submitted abstracts will go through three comprehensive reviews: (1) double-blind (at least two reviewers), (2) non-blind  and (3) participative peer reviews. Authors will receive the result of the evaluations by the reviewers of their abstracts at the end of January 2012.

If you wish to revise your submitted abstract you can do so until 30 November 2011 by going to ‘Edit account’ after you logged in to the conference website https://tnc2012.terena.org/core/user/login
Your submitted abstracts are listed at the end of your profile and you are able to edit them by clicking on the titles.

If you have any questions concerning the conference system please contact: webmaster@terena.org
Any other questions related to the conference should be addressed to: tnc2012@terena.org

Thank you for your interest in the conference.
We look forward to seeing you in Reykjavik.

Sincerely,
TNC2012 Admin Team