Dear <?= $this->values['fname'] ?> <?= $this->values['lname'] ?>,
<br><br>

<p>Thank you for submitting your paper for consideration for the <?= $this->conferenceInfo('name') ?>. 
On behalf of the programme committee, I regret to inform you that your paper "<?= $this->values['title'] ?>" has not been accepted for presentation.</p>

<p>We had a record number of papers submitted this year and the decisions were difficult to make: there were very many papers of high quality but space in the schedule was limited.</p>

<p>You may find it useful to see the following feedback about your paper from the programme committee:</p>

<p>
<hr />
<ul>
<? foreach ($this->values['reviews'] as $review): ?>
<? if ($review['comments_authors']): ?>
<li><?= $review['comments_authors'] ?></li>
<? endif; ?>
<? endforeach; ?>
</ul>
<hr />
</p>

<p>Despite this news, I hope that you will still consider participating in the <?= $this->conferenceInfo('abbreviation') ?> in Prague - registration and Call for Posters will begin on 21 February 2011.</p>

<p>
Sincerely,<br /><br />

-- <br />
Gyöngyi Horváth<br />
TERENA Conference and Workshop Organiser<br /><br />

TERENA Networking Conference 2011<br />
16 - 19 May 2011<br />
Prague, Czech Republic<br />
http://tnc2011.terena.org/<br />
#TNC2011<br /><br />

TERENA Secretariat<br />
Singel 468 D, 1017 AW Amsterdam<br />
The Netherlands<br />
T +31 20 530 44 85 F +31 20 530 44 99<br />
horvath@terena.org | www.terena.org
</p>