Dear <?= $this->values['fname'] ?> <?= $this->values['lname'] ?>,
<br><br>

<p>Thank you for submitting your paper for consideration for the <?= $this->conferenceInfo('name') ?>. 
On behalf of the programme committee, I regret to inform you that your paper "<?= $this->values['title'] ?>" has not been accepted for presentation.</p>

<p>We had a record number of papers submitted this year and the decisions were difficult to make: there were very many papers of high quality but space in the schedule was limited.</p>

<p>You may find it useful to see the following feedback about your paper from the programme committee:</p>

<p>
<hr />
<ul>
<? foreach ($this->values['reviews'] as $review): ?>
<? if ($review['comments_authors']): ?>
<li><?= $review['comments_authors'] ?></li>
<? endif; ?>
<? endforeach; ?>
</ul>
<hr />
</p>

<p>
Sincerely,<br><br>

--<br>
Gyongyi Horvath<br>
TERENA Conference and Workshop Organiser<br><br>

TERENA Networking Conference 2012<br>
21 - 24 May 2012<br>
Reykjavik, Iceland<br>
<a href="http://tnc2012.terena.org/">http://tnc2012.terena.org/</a><br>
#TNC2012<br><br>

Follow us on<br>
<a href="http://www.facebook.com/pages/TERENA/121992307863329">http://www.facebook.com/pages/TERENA/121992307863329</a><br>
<a href="http://twitter.com/TERENAcommunity">http://twitter.com/TERENAcommunity</a><br>
<a href="http://www.youtube.com/user/TERENATube">http://www.youtube.com/user/TERENATube</a><br><br>

TERENA Secretariat<br>
Singel 468 D, 1017 AW Amsterdam<br>
The Netherlands<br>
T +31 20 530 44 85 F +31 20 530 44 99<br>
<a href="mailto:horvath@terena.org">horvath@terena.org</a> | <a href="http://www.terena.org">www.terena.org</a><br>

</p>