<p>Dear <?= $this->values['fname'] . ' ' . $this->values['lname'] ?>,</p>

<p>This is an invitation to activate your account for CORE, TERENA's Conference Registration tool.</p>

<p>Please take a moment to read the following instructions carefully - they are not difficult, but there is only one oppurtunity to get it right.</p>

<?= $this->render('user/login_instructions.phtml') ?>
<?= $this->render('user/signature.phtml') ?>
