<h1>Posters</h1>
<? if ($this->authInfo()->isAdmin() ): ?>
<div class="actions"><a href="/core/poster/new" title="Add new poster">add</a></div>
<? endif; ?>
<br />
<? if ($this->grid['rows']->count() != 0): ?>
<? $i=0; ?><div id="persons">
	<ul class="longlist">
	<? foreach ($this->grid['rows'] as $posters => $poster): ?>
	<? $link = $this->url(array(
		'controller' => 'poster',
		'action' => 'delete',
		'id' => $poster->poster_id),
		'gridactions') ?>
		<li>
		<? if ($this->poster_id != $poster->poster_id): ?>
		<a href="<?= $this->url(array('controller' => 'poster', 'action' => 'show', 'id' => $poster->poster_id), 'oneitem') ?>"><?= $poster->title ?></a>
		<? else: ?>
		<span class="active"><?= $poster->title ?></span>
		<? endif; ?>
		<? if ($this->aclCheck('session', 'save')): ?><span class="delete metanav"><a href="/core/poster/edit/<?=$poster->poster_id?>">Edit</a> <a href="<?=$link?>">Delete</a></span><? endif; ?>
		</li>
		
	<? endforeach; ?>
	</ul>
</div>
<div class="clearer"></div>
<? else: ?>
<p>There are no posters in CORE.</p> 
<? endif; ?>
