      <div class="widebox">
				<div class="body">
          <h1>Hotels</h1>
          <p>Reykjavik is a popular tourist destination and the end of May is a high season, so we recommend that you make an early hotel booking. The selected conference hotels are in the centre of Reykjavik, the conference venue is located by the harbour in the city centre. The hotels are all easy to access from the airport.</p><? /* GUARANT International has been appointed as the official hotel accommodation agent for the TERENA Networking Conference (TNC2011) and will handle all related arrangements. For your convenience, a direct link to the local conference organiser's hotel booking website is available below on this page. All listed hotels have attractive discounted rates which are negotiated for the TNC2011 participants.*/ ?><br /><br />

  		<? /*
  		<p class="notice"><a href="https://tnc2011.litnet.lt/hotelbooking/ ">Book a hotel online!</a></p>
          <p>When booking your hotel, in order to receive the discounted rates offered, you have to mention the preferential code given to you by TERENA after registering for the event. For example, when booking online you should put the code into the appropriate box on the form, and also in the boxes marked ‘comments’, ‘remarks’, ‘preferential code’ or similar. If contacting hotels directly using the email addresses provided, be sure to mention the code.</p>

          <p>For example, when registering online you should put the code into the appropriate box on the form, and also in the boxes marked ‘comments’, ‘remarks’, ‘preferential code’ or similar. You may also contact the Hotels directly via the provided contact email addresses, but be sure to mention the code provided by TERENA.</p>
          */ ?>
          <h1 class="legend">Local Conference Organiser</h1>
          <p>All questions and correspondence about hotel bookings and block bookings should be sent to the local conference organiser:</p>
          <p><strong>TBC</strong></p>
          <? /*<p><strong>GUARANT International</strong><br/>
            Opletalova 22<br />
			110 00 Prague 1,<br/>
          Czech Republic<br/>
          T:+420 284 001 444<br/>
          F:+420 284 001 448<br/>
          Email:<a href="mailto:terena2011@guarant.cz">terena2011@guarant.cz</a><br/>
          Url:<a class="url" href="http://www.guarant.com/">www.guarant.com</a></p>

          <h2>Group reservations</h2>

<p>For group reservations with special rates and benefits please contact GUARANT International, the local conference organiser.</p>

          <h2>How to make a hotel reservation</h2>
          
          <p class="notice"><a href="https://secure.guarant.cz/terena2011/">BOOK YOUR HOTEL!</a></p>

<p>To make a hotel reservation, it is necessary to fill in the <a href="https://secure.guarant.cz/terena2011/">on-line Accommodation Form</a>.</p>

<p>Please note that the on-line Accommodation Form is only accessible with a password. Simply fill in the Personal Data Form and a password will be sent to you. Your password is the same for all on-line forms.
Reservations will be processed on a “first come, first-served” basis. Due to heavy demand and to the fact that distribution of rooms in many hotels is limited, accommodation cannot be guaranteed after April 12, 2011 although GUARANT International will make every effort to meet participants’ requirements.</p>

<p>Any reservation made after April 12, 2011 is subject to availability.</p>

<p>All rates quoted are per room per night including breakfast and 10 % VAT. Should VAT change before the beginning of the Conference, the Conference Secretariat will automatically change the price of your hotel room and inform you in writing about the new rate.<br />
Extras are to be paid directly at the hotel reception before departure.</p>

			<h2>Reservation confirmation</h2>
<p>A one-night deposit is required to guarantee the reservation. After the first night deposit is received, your hotel reservation will be confirmed by e-mail. The remaining amount has to be paid directly to the hotel upon check-in/out.
A one-night deposit must be paid before April 12, 2011.
In case you have special payment request, please contact GUARANT International by e-mail: <a href="mailto:terena2011@guarant.cz?subject=TNC2011%20booking">terena2011@guarant.cz</a></p>

<h2><a href="/webdemo/venue/cancellation">Hotel booking conditions</a></h2>

<p>All hotels are located within a reasonable distance from the Clarion Congress Hotel Prague (Clarion CHP).<br />
All rates quoted are per room per night including breakfast and 10 % VAT.</p>

				</div>
        <div class="closer"></div>
      </div><!--end widebox-->

     <div class="clearer"></div>

      <div class="col">
           <div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>Clarion Congress Hotel Prague (Conference venue)</h1>
                <p class="stars4"></p>
                
               </div>
              <img src="/includes/tnc2011/gfx/photos/venue/clarion.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->
            <h1>Clarion Congress Hotel Prague (Conference venue)</h1>
            <p class="notice">Fully booked!</p>
            <p>Clarion Congress Hotel Prague is located in a peaceful area directly on the metro B “Vysočanská”. The hotel offers accommodation in 559 nonsmoking rooms and luxury suites. Parking is available at extra cost.</p>
            <div class="vcard">
              <h2><span class="fn org">Address</span></h2>

              <div class="adr">
                <span class="street-address">Freyova 33</span><br />
                <span class="locality">Prague 9</span>,
                <span class="postal-code">190 00 </span>
                <div class="country-name">Czech Republic</div>
              </div>
              <div>
                <a href="http://www.cchp.cz/">www.cchp.cz</a>
              </div>
              </div><!--end vcard-->


            <h2>Internet Specifications </h2>
            <p>Wireless internet is available and it is free of charge.</p>

            <h2>Distance</h2>
            <p>The journey to the city centre takes approximately 10 minutes by metro. To check the exact location click <a href="http://maps.google.cz/maps?f=q&amp;source=s_q&amp;hl=cs&amp;geocode=&amp;q=Clarion+Congress+Hotel+Prague,+Freyova+945%2F33+110+00+Praha+&amp;aq=&amp;sll=50.110561,14.501588&amp;sspn=0.00922,0.019205&amp;brcurrent=5,0,0&amp;ie=UTF8&amp;hq=Clarion+Congress+Hotel+Prague,+Freyova+945%2F33&amp;hnear=110+00&amp;ll=50.110355,14.50161&amp;spn=0.00922,0.019205&amp;z=16&amp;iwloc=A">HERE</a>.</p>

            <h2>Prices</h2>
			Single standard room = EUR 105<br  />
            Double standard room = EUR 115<br  />
			Single executive room = EUR 135<br  />
            Double executive room = EUR 145<br  />            
					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->

<div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>Hotel Opera</h1>
                <p class="stars4"></p>
              </div>
              <img src="/includes/tnc2011/gfx/photos/venue/opera.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->

            <h1>Hotel Opera</h1>
            <p>Hotel is located just 5 minutes from the historic Old Town of Prague. Metro station and main bus station "Florenc" are located approximately 100 meters from the hotel. Parking is available at extra cost.</p>
            <div class="vcard">
              <h2><span class="fn org">Address</span></h2>

              <div class="adr">
                <span class="street-address">Tesnov 13</span><br />
                <span class="locality">Prague 1</span>,
                <span class="postal-code">110 00</span>
                <div class="country-name">Czech Republic</div>
              </div>
              <div>
                <a href="http://www.hotel-opera.cz">www.hotel-opera.cz</a>
              </div>
              </div><!--end vcard-->


            <h2>Internet Specifications </h2>
            <p>Wireless internet is available and it is free of charge.</p>

            <h2>Distance</h2>
            <p>Walking distance to the nearest metro stop: 12 minutes. Distance from venue is 7.6 km, approximately 60 minutes by foot. To check the distance from the hotel to the Conference venue click <a href="http://maps.google.cz/maps?f=d&amp;source=s_d&amp;saddr=T%C4%9B%C5%A1nov+1743%2F13,+110+00+Praha+%28Hotel+Opera%29&amp;daddr=CLARION+CONGRESS+HOTEL+PRAGUE,+Freyova,+Vyso%C4%8Dany,+Praha-Praha+9&amp;geocode=FSJY_AIdHkjcACGIq43fVPP1Tikb2LOqv5QLRzG-klXpe0jRcQ%3BFa6f_AId30bdACFaLLGAfCI6MSmR_LvWyewLRzHQKMd5ujyAUw&amp;hl=cs&amp;mra=ls&amp;sll=50.101725,14.46805&amp;sspn=0.065734,0.134926&amp;brcurrent=5,0,0&amp;ie=UTF8&amp;z=13">HERE</a>.</p>

            <h2>Prices</h2>

            Single room = EUR 75<br  />
            Double room = EUR 85<br  />

					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->

<div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>Hotel Arlington</h1>
                <p class="stars3"></p>
              </div>
              <img src="/includes/tnc2011/gfx/photos/venue/arlington.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->

            <h1>Hotel Arlington</h1>
            <p class="notice">Fully booked!</p>
            <p>Hotel Arlington is a 3-star hotel situated in Prague 9, in the neighbourhood of the newly-built high-tech Saszka sports arena. Parking is available in front of Hotel Arlington (free of charge) or in the garage (at extra cost).</p>
            <div class="vcard">
              <h2><span class="fn org">Address</span></h2>

              <div class="adr">
                <span class="street-address">Kurta Konrada 22,</span><br />
                <span class="locality">Prague 9</span>,
                <span class="postal-code">190 00</span>
                <div class="country-name">Czech Republic</div>
              </div>
              <div>
                <a href="http://www.arlingtonhotel.cz/">www.arlingtonhotel.cz</a>
              </div>
              </div><!--end vcard-->


            <h2>Internet Specifications </h2>
            <p>Wireless internet is available and it is free of charge.</p>

            <h2>Distance</h2>
            <p>Walking distance to the nearest bus stop: 10 minutes. Distance from venue is 2.2 km, approximately 27 minutes by foot. To check the distance from the hotel to the Conference venue click <a href="http://maps.google.cz/maps?f=d&amp;source=s_d&amp;saddr=Freyova+945%2F33,+Vyso%C4%8Dany,+110+00+Praha-Prague+%28Clarion+Congress+Hotel+Prague%29&amp;daddr=Kurta+Konrada+22,+190+00+Prague+9&amp;hl=cs&amp;geocode=Fa6f_AId30bdACFaLLGAfCI6MQ%3BFUyO_AIddg_dACkljEfjsuwLRzFcfF5d1EnaYA&amp;mra=pd&amp;mrcr=0&amp;dirflg=w&amp;sll=50.108167,14.494443&amp;sspn=0.019129,0.038409&amp;brcurrent=5,0,0&amp;ie=UTF8&amp;z=16">HERE</a>.</p>

            <h2>Prices</h2>

            Single room = EUR 42<br  />
            Double room = EUR 49<br  />

					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->
                
<div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>Hotel Ibis Praha Old Town</h1>
                <p class="stars3"></p>
              </div>
              <img src="/includes/tnc2011/gfx/photos/venue/ibis.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->

            <h1>Hotel Ibis Praha Old Town</h1>
            <p class="notice">Fully booked!</p>
            <p>The hotel is located in the heart of the Old Town, 5 minutes walk to the Old Town Square as well as to the Wenceslas Square, and only 150 meters from Municipal House. This excellent location gives the opportunity to discover both faces of Prague, the historical one, as well as the modern one. Parking is available at extra cost. </p>
            <div class="vcard">
              <h2><span class="fn org">Address</span></h2>

              <div class="adr">
                <span class="street-address">Na Porici 5</span><br />
                <span class="locality">Prague 1</span>,
                <span class="postal-code">110 00</span>
                <div class="country-name">Czech Republic</div>
              </div>
              <div>
                <a href="http://oldtown.hotelibis.cz/hotely/ibis/10-0-1-ibis-info">oldtown.hotelibis.cz</a>
              </div>
              </div><!--end vcard-->


            <h2>Internet Specifications </h2>
            <p>Wireless internet is available and it is free of charge.</p>

            <h2>Distance</h2>
            <p>From metro station Namesti Republiky situated 200 m walk away from the hotel take a metro (line B) and go 6 stops to the metro station Vysocanska. Clarion CHP is located directly on the metro station. The journey should take up to 15 minutes. To check the distance from the hotel to the Conference venue click <a href="http://maps.google.cz/maps?f=d&amp;source=s_d&amp;saddr=Clarion+Congress+Hotel+Prague,+Freyova,+%E3%83%B4%E3%82%A3%E3%82%BD%E3%83%81%E3%83%A3%E3%83%8B,+Prague-Prague+9&amp;daddr=Ibis+Old+Town+Na+Porici+5,+Prague+1&amp;hl=cs&amp;geocode=Fa6f_AId30bdACFaLLGAfCI6MQ%3BFbhN_AIdqDLcACFjCDwLetXR6w&amp;mra=ls&amp;sll=49.930008,15.369873&amp;sspn=4.915405,9.832764&amp;brcurrent=5,0,0&amp;ie=UTF8&amp;z=14">HERE</a>.</p>

            <h2>Prices</h2>

            Single room = EUR 80<br  />
            Double room = EUR 90<br  />

					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->
             
            </div>  <!--end col-->


      <div class="col2">

<div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>Design hotel Elephant</h1>
                <p class="stars4"></p>
              </div>
              <img src="/includes/tnc2011/gfx/photos/venue/elephant.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->

            <h1>Design hotel Elephant</h1>
            <p>Located in the heart of historic Prague, Hotel Elephant is defined by its blend of contemporary design and elegant styling. The hotel offers 80 superior rooms and 20 junior suites, all furnished to an exceptional standard. Underground secure parking is also available for hotel guests at extra cost.</p>
            <div class="vcard">
              <h2><span class="fn org">Address</span></h2>

              <div class="adr">
                <span class="street-address">Na Florenci 29</span><br />
                <span class="locality">Prague 1</span>,
                <span class="postal-code">110 00</span>
                <div class="country-name">Czech Republic</div>
              </div>
              <div>
                <a href="http://www.designhotel-elephant.com/">www.designhotel-elephant.com</a>
              </div>
              </div><!--end vcard-->

            <h2>Internet Specifications </h2>
            <p>Wireless internet is available and it is free of charge.</p>

            <h2>Distance</h2>
            <p>Take a metro line B from Florenc station and go to the station Vysocanska (5 stops). Clarion CHP is situated directly on the metro station. The journey should take approximately 12 min. To check the distance from the hotel to the Conference venue click <a href="http://maps.google.cz/maps?f=d&amp;source=s_d&amp;saddr=Freyova+945%2F33,+Vyso%C4%8Dany,+110+00+Praha-Prague+%28Clarion+Congress+Hotel+Prague%29&amp;daddr=Design+hotel+Elephant,+Na+Florenci+29,+110+00+Prague+1&amp;geocode=Fa6f_AId30bdACFaLLGAfCI6MQ%3BFQtP_AIdG0vcACGJKO1J8s2Irg&amp;hl=cs&amp;mra=ls&amp;sll=50.09989,14.46979&amp;sspn=0.038264,0.076818&amp;brcurrent=5,0,0&amp;ie=UTF8&amp;z=14">HERE</a>.</p>

            <h2>Prices</h2>

            Single room = EUR 90<br  />
            Double room = EUR 90<br  />

					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->
        
      

      	<div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>Hotel AXA</h1>
                <p class="stars3"></p>
              </div>
              <img src="/includes/tnc2011/gfx/photos/venue/axa.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->

            <h1>Hotel AXA</h1>
            <p>The hotel is ideally situated within walking distance of the Prague's historic center and main shopping streets and malls. Parking is available at extra cost. </p>
            <div class="vcard">
              <h2><span class="fn org">Address</span></h2>

              <div class="adr">
                <span class="street-address">Na Poříčí 40</span><br />
                <span class="locality">Prague 1</span>,
                <span class="postal-code">110 00</span>
                <div class="country-name">Czech Republic</div>
              </div>
              <div>
               <a href="http://www.axa-hotel.cz/">www.axa-hotel.cz</a>
              </div>
              </div><!--end vcard-->


            <h2>Internet Specifications </h2>
            <p>Wireless internet access is available near the reception in “Wi-Fi corner” and it is free of charge. </p>

            <h2>Distance</h2>
            <p>Take a metro line B from Florenc station and go to the station Vysocanska (5 stops). Clarion CHP is situated directly on the metro station. The journey should take approximately 12 min. To check the distance from the hotel to the Conference venue click <a href="http://maps.google.cz/maps?f=d&amp;source=s_d&amp;saddr=Freyova+945%2F33,+Vyso%C4%8Dany,+110+00+Praha-Prague+%28Clarion+Congress+Hotel+Prague%29&amp;daddr=HOTEL+AXA+s.r.o.,+Na+po%C5%99%C3%AD%C4%8D%C3%AD,+Nov%C3%A9+M%C4%9Bsto,+Praha&amp;geocode=Fa6f_AId30bdACFaLLGAfCI6MQ%3BFXdP_AIdK0XcACHEtu-kOu7sZA&amp;sll=50.110011,14.501953&amp;sspn=0.612091,1.229095&amp;brcurrent=5,0,0&amp;hl=cs&amp;mra=ls&amp;ie=UTF8&amp;z=14">HERE</a>.</p>

            <h2>Prices</h2>

            Single room = EUR 62<br  />
            Double room = EUR 67<br  />

					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->


         <div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>Hotel Esprit</h1>
                <p class="stars3"></p>
              </div>
              <img src="/includes/tnc2011/gfx/photos/venue/esprit.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->

            <h1>Hotel Esprit</h1>
            <p>Hotel Esprit is located in a peaceful part of Prague 9 – Vysocany, 200 m from metro station Ceskomoravska (line B). Hotel Esprit offers 62 rooms. Parking is available at extra cost. </p>
            <div class="vcard">
              <h2><span class="fn org">Address</span></h2>

              <div class="adr">
                <span class="street-address">Lihovarská 8</span><br />
                <span class="locality">Prague 9</span>,
                <span class="postal-code">190 00</span>
                <div class="country-name">Czech Republic</div>
              </div>
              <div>
                <a href="http://www.hotel-esprit.cz/">www.hotel-esprit.cz</a>
              </div>
              </div><!--end vcard-->


            <h2>Internet Specifications </h2>
            <p>Wireless internet is available and it is free of charge.</p>

            <h2>Distance</h2>
            <p>Take a metro line B from Ceskomoravska station. Clarion CHP is situated only 1 stop away directly on the metro station Vysocanska. The journey should take up to 5 minutes. To check the distance from the hotel to the Conference venue click <a href="http://maps.google.cz/maps?f=d&amp;source=s_d&amp;saddr=Freyova+945%2F33,+Vyso%C4%8Dany,+110+00+Praha-Prague+%28Clarion+Congress+Hotel+Prague%29&amp;daddr=Lihovarsk%C3%A1+8,+Libe%C5%88,+Praha-Praha+9&amp;geocode=Fa6f_AId30bdACFaLLGAfCI6MQ%3BFTSI_AIdRg3dACnlDubVsuwLRzH2fosJb3QV5A&amp;hl=cs&amp;mra=ls&amp;sll=50.013109,14.369638&amp;sspn=0.306666,0.614548&amp;brcurrent=5,0,0&amp;ie=UTF8&amp;z=16">HERE</a>.</p>

            <h2>Prices</h2>

            Single room = EUR 40<br  />
            Double room = EUR 53<br  />

					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->

	  </div><!--end col-->

      <div class="col">

<div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>Hotel Olympik</h1>
                <p class="stars4"></p>
              </div>
              <img src="/includes/tnc2011/gfx/photos/venue/olympik.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->

            <h1>Hotel Olympik</h1>
            <p class="notice">Fully booked!</p>
            <p>Hotel Olympik is located within a quiet area of the Prague 8 city district just 10 minutes ride from the historical city centre. Tram and metro stops are located just 300 metres from the hotel. Parking is available at extra cost.</p>
            <div class="vcard">
              <h2><span class="fn org">Address</span></h2>

              <div class="adr">
                <span class="street-address">Sokolovska 138</span><br />
                <span class="locality">Prague 8</span>,
                <span class="postal-code">186 76</span>
                <div class="country-name">Czech Republic</div>
              </div>
              <div>
               <a href="http://www.olympik.cz/">www.olympik.cz</a>
              </div>
              </div><!--end vcard-->

            <h2>Internet Specifications </h2>
            <p>Internet connection is available at extra cost.</p>

            <h2>Distance</h2>
            <p>Take a metro line B from Invalidovna station and go to the station Vysocanska (3 stops). Clarion CHP is situated directly on the metro station. The journey should take approximately 8 min. To check the distance from the hotel to the Conference venue click <a href="http://maps.google.cz/maps?f=d&amp;source=s_d&amp;saddr=Clarion+Congress+Hotel+Prague,+Freyova,+%E3%83%B4%E3%82%A3%E3%82%BD%E3%83%81%E3%83%A3%E3%83%8B,+Prague-Prague+9&amp;daddr=Sokolovsk%C3%A1+615%2F138,+186+00+Praha+8-Karl%C3%ADn+%28Hotel+OLYMPIK%29&amp;geocode=Fa6f_AId30bdACFaLLGAfCI6MQ%3BFSVw_AIdF8XcACHHearMf0xvEA&amp;hl=cs&amp;mra=pd&amp;mrcr=0&amp;sll=50.104396,14.485044&amp;sspn=0.03826,0.076818&amp;brcurrent=5,0,0&amp;ie=UTF8&amp;z=15">HERE</a>.</p>

            <h2>Prices</h2>

            Single room = EUR 70<br  />
            Double room = EUR 80<br  />

					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->

<div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>Hotel Carol</h1>
                <p class="stars3"></p>
              </div>
              <img src="/includes/tnc2011/gfx/photos/venue/carol.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->

            <h1>Hotel Carol</h1>
            <p class="notice">Fully booked!</p>
            <p>Hotel Carol is located in a peaceful street in Vysocany, outside the busy centre. Metro station is located only 250m from the hotel. Hotel Carol offers accommodation in 52 comfortable single, double and triple rooms. Parking is available at extra cost.</p>
            <div class="vcard">
              <h2><span class="fn org">Address</span></h2>

              <div class="adr">
                <span class="street-address">Kurta Konrada 12</span><br />
                <span class="locality">Prague 9</span>,
                <span class="postal-code">190 00</span>
                <div class="country-name">Czech Republic</div>
              </div>
              <div>
                <a href="http://www.hotelcarol.com/">www.hotelcarol.com </a>
                              </div>
              </div><!--end vcard-->


            <h2>Internet Specifications </h2>
            <p>Wireless internet is available and it is free of charge.</p>

            <h2>Distance</h2>
            <p>From tram stop Divadlo Gong situated 2 minutes walk away from the hotel take a tram No.: 19 and get off at stop Nadrazi Vysocany (2nd stop). The journey should take approximately 5 minutes. To check the distance from the hotel to the Conference venue click <a href="http://maps.google.cz/maps?f=d&amp;source=s_d&amp;saddr=Freyova+945%2F33,+Vyso%C4%8Dany,+110+00+Praha-Prague+%28Clarion+Congress+Hotel+Prague%29&amp;daddr=Kurta+Konrada+12,+Prague+9&amp;geocode=Fa6f_AId30bdACFaLLGAfCI6MQ%3BFbyL_AIdlRHdACntGaQYs-wLRzFmN4Te2S58Jw&amp;hl=cs&amp;mra=ls&amp;sll=50.10776,14.49466&amp;sspn=0.009564,0.019205&amp;brcurrent=5,0,0&amp;ie=UTF8&amp;z=16">HERE</a>.</p>

            <h2>Prices</h2>

            Single room = EUR 60<br  />
            Double room = EUR 68<br  />

					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->

        <div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>Hotel Olympik Tristar</h1>
                <p class="stars3"></p>
              </div>
              <img src="/includes/tnc2011/gfx/photos/venue/olympikt.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->

            <h1>Hotel Olympik Tristar</h1>
            <p class="notice">Fully booked!</p>
            <p>The hotel is situated in a quiet residential quarter on metro line B, just 10 minutes by public transportation from the historical centre of Prague. Parking is available at extra cost. </p>
            <div class="vcard">
              <h2><span class="fn org">Address</span></h2>

              <div class="adr">
                <span class="street-address">U Sluncové 14</span><br />
                <span class="locality">Prague 8</span>,
                <span class="postal-code">186 76</span>
                <div class="country-name">Czech Republic</div>
              </div>
              <div>
               <a href="http://www.olympik.cz/tristar/">www.olympik.cz/tristar</a>
                             </div>
              </div><!--end vcard-->


            <h2>Internet Specifications </h2>
            <p>Wireless internet is available at extra charge.</p>

            <h2>Distance</h2>
            <p>Hotel Olympik Tristar is situated near the metro station (line B) – Invalidovna (300m). Clarion CHP is situated just 3 stops away, directly on the metro station “Vysočanská”. The journey takes approximately 8 minutes.  To check the distance from the hotel to the Conference venue click <a href="http://maps.google.cz/maps?f=d&amp;source=s_d&amp;saddr=Freyova+945%2F33,+Vyso%C4%8Dany,+110+00+Praha-Prague+%28Clarion+Congress+Hotel+Prague%29&amp;daddr=U+Sluncov%C3%A9+14,+186+76+Praha+8&amp;geocode=Fa6f_AId30bdACFaLLGAfCI6MQ%3BFRRy_AIdtc3cACnNNoKDV5MLRzEQRSi1Zm4wBA&amp;hl=cs&amp;mra=pd&amp;mrcr=0&amp;dirflg=w&amp;sll=50.104545,14.486091&amp;sspn=0.03826,0.076818&amp;brcurrent=5,0,0&amp;ie=UTF8&amp;z=15">HERE</a>.</p>

            <h2>Prices</h2>

            Single room = EUR 65<br  />
            Double room = EUR 75<br  />

					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->

<div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>Hotel Vysočanský pivovar</h1>
                <p class="stars2"></p>
              </div>
              <img src="/includes/tnc2011/gfx/photos/venue/vysocansky.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->

            <h1>Hotel Vysočanský pivovar</h1>
            <p class="notice">Fully booked!</p>
            <p>Blending cosy atmosphere and warm hospitality, the hotel Vysočanský Pivovar is an ideal place for a fun filled vacation. Conveniently located in the centre of Vysočany, this property is close to shopping centers and restaurants. Parking is available at extra cost. </p>
            <div class="vcard">
              <h2><span class="fn org">Address</span></h2>

              <div class="adr">
                <span class="street-address">Freyova 12/1</span><br />
                <span class="locality">Prague 9</span>,
                <span class="postal-code">190 00</span>
                <div class="country-name">Czech Republic</div>
              </div>
              <div>
               <a href="http://www.hotel-pivovar.cz/">www.hotel-pivovar.cz</a>
              </div>
              </div><!--end vcard-->


            <h2>Internet Specifications </h2>
            <p>Wireless internet is available at extra charge.</p>

            <h2>Distance</h2>
            <p>Hotel is located within 5 minutes walking distance of the Conference venue. To check the distance from the hotel to the Conference venue click <a href="http://maps.google.cz/maps?f=d&amp;source=s_d&amp;saddr=Freyova+945%2F33,+Vyso%C4%8Dany,+110+00+Praha-Prague+%28Clarion+Congress+Hotel+Prague%29&amp;daddr=Freyova+1%2F12,+190+00+Praha+9-Vyso%C4%8Dany&amp;geocode=Fa6f_AId30bdACFaLLGAfCI6MQ%3BFRGU_AIdMkzdACm7kvqAyewLRzGcP8thFRqlMQ&amp;hl=cs&amp;mra=pd&amp;mrcr=0&amp;dirflg=w&amp;sll=50.108895,14.502064&amp;sspn=0.009564,0.019205&amp;brcurrent=5,0,0&amp;ie=UTF8&amp;z=17.">HERE.</a></p>

            <h2>Prices</h2>
			Single room = EUR 30<br  />
            Double room = EUR 44<br  />
			Double room for single use = EUR 40<br />
			
					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->

		</div>  <!--end col-->
*/ ?>

      <div class="clearer"></div>




     <div class="widebox">
		  	<div class="body">
        <div class="legend">
	        <h1>TNC2012 Area Map</h1>
          <h1 class="legend">Legend</h1>
          <ul class="legend">
            <li id="gm_venue">Venue</li>
            <li id="gm_train">Transportation</li>
            <li id="gm_hotel">Hotels (tbc)</li>
          </ul>
          <? /*<h1 class="legend">Locations</h1>
          <ol>
             <li>Design Hotel Elephant</li>
            <li>Hotel Olympik</li>
            <li>Hotel Arlington</li>
            <li>Hotel AXA</li>
            <li>Hotel Carol</li>
            <li>Hotel Ibis Praha Old Town</li>
            <li>Hotel Esprit</li>
            <li>Hotel Olympik Tristar</li>
            <li>Hotel Vysocansky Pivovar</li>
           

          </ol>*/ ?>

        <div>
          <p>Click on the appropriate marker to display more detailed information, pan and zoom using the controls top left.</p>
          <p>Find more detailed information about hotels above on this page.</p>
        </div>
		</div>
        <div id="map"></div>

        <div class="clearer"></div>

      	</div>
        <div class="closer"></div>
      </div><!--end widebox-->
