    	<div class="bigbox">
				<div class="body">
          <h1>Getting to Reykjavik</h1>
          <p>Travel from Europe to Iceland is easy with Iceland’s international airport at Keflavik only about three hours away from London, Paris, Amsterdam, Copenhagen, Oslo and Stockholm. Iceland’s national carrier, Icelandair, operates regular flights from many European cities and a low-budget airline, Iceland Express, flies to Keflavik Airport from Copenhagen-Kastrup and London-Stansted and from many other European cities during the period of June  to August.  Scandinavian Airlines operates flights from Oslo to Iceland.  Delta Airlines will start this summer to offer services from New York to Keflavik.
We recommend using flight search engines like <a href="http://www.dohop.com/">www.dohop.com</a> to hunt for good prices or to arrange flight connections to Iceland.</p>
  		<p>Most of the social event locations and all recommended hotels are in the city centre.</p>
  		<p>Although it is easy to walk almost everywhere within the city of Reykjavik, visitors can also use the public transport: <a href="http://www.straeto.is/english">http://www.straeto.is/english</a>.</p>
  		</div>
        <div class="closer"></div>
      </div><!--end bigbox-->
     
     <div class="clearer"></div>
    	
	<div class="bigbox">
      	<div class="body"	>
		<h1>Photos of Iceland</h1>
		<?= $this->render('_shared/venue_pictures.phtml'); ?>
      	</div><!--end bigbox body-->
		<div class="closer"></div>
	</div>

    </div>
    <? /*<div id="sidebar">
    	<div class="box">
    	<?= $this->render('_shared/venue_vcard.phtml'); ?>
      	<div class="closer"></div>
	  	</div><!--end box-->*/ ?>

      <div class="box">
      	<div class="body" id="accordion">
          <h1>Getting to Reykjavik by...</h1>
          <h2 class="toggler atStart">Plane</h2>
          <p class="element atStart">
			    The international airport Keflavik (KEF) is located 45 km from the city centre. The best way to reach City Centre is by bus, takes the same time and effort as with a taxi. The price of a taxi from the airport to the venue or to hotels should be about 60 Euro. Taxis are available outside the terminal for any destination.<br />Flybus is perated all year daily from Keflavik Airport to Reykjavik in connection with all arriving flights. The Flybus is located right outside the Keflavik International Airport. The Flybus brings passengers to the BSI Bus Terminal in Reykjavik near to the capital´s centre. From there passengers are brought to some of the major hotels and guesthouses in Reykjavik. Kindly note that not all hotels and gueasthouses are provided with this service. Duration: 40 - 50 minutes.<br />
		  </p>
			<p>Keflavik International Airport<br />
			235 Keflavikurflugvollur<br /> 
			Iceland<br />
			Tel.: +354 425 6000<br />
			Fax.: +354 425 6010<br />
			Webpage: <a href="http://www.kefairport.is/english/">www.kefairport.is</a></p>
					
					<h2 class="toggler atStart">Taxis</h2>
			<p class="element atStart">
			Taxis are very expensive in Iceland. They can be hailed on the street or visitors can ask local hotel or restaurant staff to call taxis to come pick them up.  Visitors should note that taxi fares are standardized throughout Reykjavik and fares should be posted in every cab.<br /> 
			Taxis:<br /><br />

    <strong>A-Stöðin Airport taxi</strong><br />+354 420 1212 or +354 520 1212<br />
    Web: <a href="http://www.airporttaxi.is/">www.airporttaxi.is</a><br />
    Email: taxi@airporttaxi.is<br /><br />
    <strong>Hreyfill Bæjarleiðir Taxi</strong><br />+354 421 4141<br />
    Web: <a href="http://www.hreyfill.is/hreyfill/en/">www.hreyfill.is</a></p>
	
					
        </div><!--body-->
        <div class="closer"></div>
<div class="clearer"></div>
    
        

