 
<div id="content">
           
     <? /*<div class="bigbox">
      	<div id="hp" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.hp.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/hp_big.jpg" /></a>
            
          </div>
          <div class="description">
            <h1>HP</h1>
            <p>HP is a technology company that operates in more than 170 countries around the world. We explore how technology and services can help people and companies address their problems and challenges, and realize their possibilities, aspirations and dreams. We apply new thinking and ideas to create more simple, valuable and trusted experiences with technology, continuously improving the way our customers live and work.

No other company offers as complete a technology product portfolio as HP. We provide infrastructure and business offerings that span from handheld devices to some of the world's most powerful supercomputer installations. We offer consumers a wide range of products and services from digital photography to digital entertainment and from computing to home printing. This comprehensive portfolio helps us match the right products, services and solutions to our customers' specific needs.</p>
            <p>For more information, visit: <a href="http://www.hp.com/">www.hp.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>*/ ?>
      
      <div class="bigbox">
      	<div id="template" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.terena.org/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/sponsor-template.jpg" /></a>
            
          </div>
          <div class="description">
            <h1>Your company name</h1>
            <p>Short description of your company.</p>
            <p>For more information, visit: <a href="http://www.terena.org/">Your company's url</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <? /*<div class="bigbox">
      	<div id="telindus" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://http://www.telindus.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/telindus.gif" /></a>
            
          </div>
          <div class="description">
            <h1>Telindus</h1>
            <p>Telindus is an international company that offers to Large Companies,
Public Administrations and Telecommunications Operators a complete
technological proposal based on 5 pillars: Emergent IT architectures,
Unified Communications, Systems and Storage, Video and IP TV and IT
Security. Technological proposal completed with consulting, Installation
and Training, Operation, Integrated Maintenance and Management Services.</p>
            <p>For more information, visit: <a href="http://www.telindus.com/">www.telindus.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>*/ ?>
      
       
      
      
      <? /*<div class="bigbox">
      	<div id="globalcrossing" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.globalcrossing.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/globalcrossing.gif" /></a>
  
          </div>
          <div class="description">
            <h1>Global Crossing</h1>
            <p>Global Crossing provides a full range of managed telecommunications services in a secure environment ideally suited for IP-based enabled businesses. Across this world-class network the company provides industry leading, cost effective solutions that complement your existing network. We offer our enterprise customers a full suite of regional and global value-added solutions ranging from IP connectivity and business continuity, to fully owned and operated managed solutions. Our flexible service options allow you to focus on your own high-priority business initiatives, while leaving all, or part, of the day-to-day management of your communications to Global Crossing.</p>
            <p>For more information, visit: <a href="http://www.globalcrossing.com/">www.globalcrossing.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>*/ ?>
      
      <? /*
      <div class="bigbox">
      	<div id="nokiasiemens" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.nokiasiemensnetworks.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/nsn.jpg" /></a>
  
          </div>
          <div class="description">
            <h1>Nokia Siemens Networks</h1>
            <p>Nokia Siemens Networks is a leading global enabler of telecommunications services. With its focus on innovation and sustainability, the company provides a complete portfolio of mobile, fixed and converged network technology, as well as professional services including consultancy and systems integration, deployment, maintenance and managed services. It is one of the largest telecommunications hardware, software and professional services companies in the world. Operating in 150 countries, its headquarters are in Espoo, Finland.</p>
            <p>For more information, visit: <a href="http://www.nokiasiemensnetworks.com/">www.nokiasiemensnetworks.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <div class="bigbox">
      	<div id="cisco" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.cisco.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/cisco.jpg" /></a>
  
          </div>
          <div class="description">
            <h1>Cisco</h1>
            <p>Cisco (NASDAQ: CSCO) enables people to make powerful connections-whether in business, education, philanthropy, or creativity. Cisco hardware, software, and service offerings are used to create the Internet solutions that make networks possible-providing easy access to information anywhere, at any time.Cisco was founded in 1984 by a small group of computer scientists from Stanford University. Since the company's inception, Cisco engineers have been leaders in the development of Internet Protocol (IP)-based networking technologies. Today, with more than 65,225 employees worldwide, this tradition of innovation continues with industry-leading products and solutions in the company's core development areas of routing and switching, as well as in advanced technologies.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <div class="bigbox">
      	<div id="huawei" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.huawei.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/huawei.jpg" /></a>
  
          </div>
          <div class="description">
            <h1>Huawei</h1>
            <p>Huawei is a leading telecom solutions provider. Through continuous customer-centric innovation, we have established end-to-end advantages in Telecom Network Infrastructure, Application &amp; Software, Professional Services and Devices. With comprehensive strengths in wireline, wireless and IP technologies, Huawei has gained a leading position in the All-IP convergence age. Our products and solutions have been deployed in over 100 countries and have served 45 of the world's top 50 telecom operators, as well as one third of the world's population.<br />

Huawei's vision is to enrich life through communication. By leveraging our experience and expertise in the telecom sector, we help bridge the digital divide and give people the opportunity to join the information age, regardless of their geographic origin. In order to tackle increasing climate challenges, Huawei has deployed a wide range of green solutions that enable customers to reduce power consumption and carbon emissions, contributing to the sustainable development of the social economy and the environment.</p>
            <p>For more information, visit: <a href="http://www.huawei.com/">www.huawei.com/</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
          
      <div class="bigbox">
      	<div id="advaoptical" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.advaoptical.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/adva.gif" /></a>
            
          </div>
          <div class="description">
            <h1>ADVA Optical Networking</h1>
            <p>ADVA Optical Networking will be exhibiting at the conference. Please come and meet us and find out how our innovative Optical+Ethernet solutions make networks more manageable, operate more efficiently and possess considerably higher bandwidth for high-volume data transmission.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <div class="bigbox">
      	<div id="juniper" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.juniper.net/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/juniper.jpg" /></a>
            
          </div>
          <div class="description">
            <h1>Juniper Networks</h1>
            <p>Juniper Networks is the leader in high-performance networking. Juniper offers innovative businesses a high-performance network infrastructure to help them create a responsive and trusted environment for accelerating the deployment of services and applications over a single network. The top 65 service providers, 96 of the Fortune 100, and large government agencies and institutions are among the many demanding businesses that rely on Juniper Networks to quickly meet their high-performance business requirements. The company is headquartered in Sunnyvale, California. Juniper Networks is publicly traded on NYSE under the symbol JNPR.</p>
            <p>For more information, visit: <a href="http://www.juniper.net/">www.juniper.net</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
            <div class="bigbox">
      	<div id="ripe" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.ripe.net/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/ripe.jpg" /></a>
  
          </div>
          <div class="description">
            <h1>RIPE NCC</h1>
            <p>The RIPE NCC is an independent, not-for-profit membership organisation that supports the infrastructure of the Internet through technical coordination in its service region. The RIPE NCC serves as the Regional Internet Registry (RIR) for Europe, the Middle East and parts of Central Asia, providing global Internet resources (IPv4, IPv6 and AS Number resources) and related services to its members. Membership is open to all, and is made up mainly of Internet Service Providers (ISPs), telecommunication organisations, educational institutions and large corporations. Among its coordination activities, the RIPE NCC maintains the RIPE Database, manages one of the 13 root name servers (K-root) and coordinates support for ENUM delegations.</p>
            <p>For more information, visit: <a href="http://www.ripe.net/">www.ripe.net</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
            <div class="bigbox">
      	<div id="vidyo" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.vidyo.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/vidyo.gif" /></a>
  
          </div>
          <div class="description">
            <h1>Vidyo Inc.</h1>
            <p>Vidyo, Inc. pioneered Personal Telepresence, enabling natural, multi-point videoconferences on room systems, desktop computers, laptops, Netbooks, and smart phones. Vidyo´s patented VidyoRouter architecture delivers the only available H.264/SVC solution that eliminates an MCU while providing the industry´s best error resilience (click here to see a video) and lowest latency videoconferencing solution over the Internet and wireless networks. Learn more at www.vidyo.com. Follow Vidyo on Twitter@VidyoConf.</p> 
            <p>For more information, visit: <a href="http://www.vidyo.com/">www.vidyo.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <div class="bigbox">
      	<div id="customconnect" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://custom-connect.net/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/custom_connect.jpg" /></a>
  
          </div>
          <div class="description">
            <h1>Custom Connect</h1>
            <p>Custom Connect is your partner in the delivery of high performance network solutions with a strong focus on low latency networks. Custom Connect provides worldwide carrier neutral network infrastructures resulting in low latency services which are delivered together with almost every Tier 1 carrier. As an independent connectivity reseller we differentiate ourselves by maintaining a neutral position, not bound to any hardware vendor or carrier.<br />
The following services are delivered:<br />
- Dark Fibre<br />
- Wavelengths<br />
- Ethernet<br />
- Metro connectivity<br />
- Long haul connectivity<br />
- 24x7 Support<br />
- Project management</p> 
            <p>For more information, visit: <a href="http://custom-connect.net/">http://custom-connect.net/</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
            
      <div class="bigbox">
      	<div id="ciena" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="www.ciena.com/researchandeducation"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/ciena.jpg" /></a>
  
          </div>
          <div class="description">
            <h1>Ciena Corporation</h1>
            <p>Ciena Corporation, the network specialist, provides advanced optical and Ethernet products and services to enable the creation of robust, automated and fully redundant networks for researchers worldwide. Our solutions feature programmability to enable provisioning of any service on any port, automated management, integrated support of OTN and integrated data switching functionality. Ciena collaborates with leading institutions to provide the research and education community optimized networks that minimize cost and complexity, with initiatives supporting the implementation of intelligent control plane technologies, interoperability and scalability from Ethernet to 100G and beyond.</p> 
            <p>For more information, visit: <a href="www.ciena.com/researchandeducation">www.ciena.com/researchandeducation</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div> 
      */ ?>     
      
     <? /*<div class="bigbox">
      	<div id="skaidula" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.skaidula.lt/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/skaidula.jpg" /></a>
  
          </div>
          <div class="description">
            <h1>Skaidula</h1>
            <p>CSkaidula was established in 1989 and began its activity from Optical Time Domain Reflectometers producing and local fibre optic networking. In 1994 Skaidula started to work in the branch of private communication systems as authorized dealer of Siemens OY. In the same time we became representatives of Reichle & De-Massari (Switzerland) in Lithuania and begun to supply with qualitative line distribution equipment. In 1995 GSM network was established in Lithuania. From that time JSC Skaidula started to sell mobile telephones and fax/data transmitting adaptors. Presently our company is among biggest information and telecommunication technologies providing companies. Skaidula realizes the complex solutions from product design to its implementation and maintenance. Projects include wide range of services beginning with installation of local networks and ending with implementation of telecommunication networks and information systems.</p> 
            <p>For more information, visit: <a href="http://www.skaidula.lt">www.skaidula.lt</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>*/ ?>
      
        <? /*<div class="bigbox">
      	<div id="ekinops" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.ekinops.net/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/ekinops.jpg" /></a>
            
          </div>
          <div class="description">
            <h1>Ekinops</h1>
            <p>Ekinops is a leading designer and supplier of next generation optical transport equipment for service providers and enterprise customers. The Ekinops 360 Dynamic, Multi-Reach Transport System provides DWDM and CWDM on a single platform that addresses Metro, Regional, and Long Haul applications. Using the Ekinops 360 carrier-grade system, operators can increase transport capacity of their networks – CWDM, DWDM, Ethernet, ESCON, Fiber Channel, SONET/SDH, and uncompressed video (HD-SDI, SD-SDI, ASI) – through the industry’s most efficient aggregation of services. The company is headquartered in Lannion, France, with offices in Europe, the USA and Asia.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div> */ ?>
       
<? /*
     <div class="bigbox">
      	<div id="infinera" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.infinera.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/infinera.jpg" /></a>
  
          </div>
          <div class="description">
            <h1>Infinera Corporation</h1>
            <p>Infinera pioneered "Digital Optical Networking", a new approach to optical telecommunications enabled by photonic integration.  Digital Optical Networking combines dense wave division multiplexing (DWDM) scalability, digital bandwidth management and protection, and GMPLS-based networking intelligence.  Infinera's systems are unique in their use of a breakthrough semiconductor technology: the Photonic Integrated Circuit (PIC).  Service providers who use Infinera systems benefit from simpler planning, engineering, and operations; faster and easier scalability; and much more network flexibility than is possible using conventional optical systems.  The Infinera DTN optical platform, based on our Photonic Integrated Circuits (PICs), is today delivering Ethernet, SONET/SDH, and wavelength transport services in long-haul, regional, and metro core networks around the world.</p>
             <p>For more information, visit: <a href="http://www.infinera.com">www.infinera.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      */ ?>
    
    <? /*<div class="bigbox">
      	<div id="rediris" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.rediris.es/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/rediris.gif" /></a>
  
          </div>
          <div class="description">
            <h1>RedIRIS</h1>
            <p>RedIRIS is the Spanish NREN (National Research and Educational Network) in charge of providing advanced communication services to the national scientific and academic community.

RedIRIS has more than 300 affiliated institutions, essentially universities and public research centers, that become part of this community through the signature of an affiliation agreement.</p>
<p>For more information, visit: <a href="http://www.rediris.es">www.rediris.es</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>*/ ?>
   
   <? /*<div class="bigbox">
      	<div id="comodo" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.comodo.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/comodo.jpg" /></a>
  
          </div>
          <div class="description">
            <h1>Comodo</h1>
            <p>Comodo is Creating Trust Online by providing software and services that enable e-commerce merchants, enterprises, organizations, and individual consumers to interact and conduct business via the Internet safely and securely. Comodo secures and authenticates the online transactions, communications and endpoints for over 200,000 business customers and millions of users of our desktop security software. Continual innovation, core competencies in PKI, authentication, and malware detection and prevention, plus our commitment to reversing the growth of Internet-crime distinguish Comodo as a vital player in the Internet's ongoing development.</p>
<p>For more information, visit: <a href="http://www.comodo.com">www.comodo.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>*/ ?>
      
      <? /*
      <div class="bigbox">
      	<div id="comodo" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.comodo.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/comodo.jpg" /></a>
  
          </div>
          <div class="description">
            <h1>Comodo</h1>
            <p>Comodo is Creating Trust Online by providing software and services that enable e-commerce merchants, enterprises, organizations, and individual consumers to interact and conduct business via the Internet safely and securely. Comodo secures and authenticates the online transactions, communications and endpoints for over 200,000 business customers and millions of users of our desktop security software. Continual innovation, core competencies in PKI, authentication, and malware detection and prevention, plus our commitment to reversing the growth of Internet-crime distinguish Comodo as a vital player in the Internet's ongoing development.</p>
<p>For more information, visit: <a href="http://www.comodo.com">www.comodo.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <div class="bigbox">
      	<div id="extreme" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.extremenetworks.com/researchandeducation"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/extreme.gif" /></a>
  
          </div>
          <div class="description">
            <h1>Extreme Networks</h1>
            <p>Extreme Networks delivers affordable and secure Ethernet solutions for Data, IP-Telephony and Wireless applications. Our commitment to open networking sets us apart from alternatives by delivering meaningful insight and unprecedented control to applications and services. We believe openness is the best foundation for freedom, flexibility, and choice. Visit us in the exhibition area and learn more about our Go Green Initiatives, Network Automation and Provider Backbone Bridging. We’ll be happy to share our Passion for Networking with you.</p>
<p>For more information, visit: <a href="http://www.extremenetworks.com/researchandeducation">www.extremenetworks.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
         
   <div class="bigbox">
      	<div id="level3" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.level3.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/level3.gif" /></a>
  
          </div>
          <div class="description">
            <h1>Level 3 Communications</h1>
            <p>Level 3 Communications, Inc. (NASDAQ: LVLT) is a premier international provider of fiber-based communications services. Enterprise, wholesale, government and content customers rely on Level 3 to deliver advanced communications solutions with an industry-leading combination of efficiency and quality over one of the world’s most scalable end-to-end networks.</p>
<p>For more information, visit: <a href="http://www.level3.com">www.level3.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
   <div class="bigbox">
      	<div id="cesnet" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.cesnet.cz/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/cesnet.jpg" /></a>
  
          </div>
          <div class="description">
            <h1>CESNET</h1>
            <p>The Czech National Research and Education Network. The members of this association use, manage and develop the network.
 </p>
<p>For more information, visit: <a href="http://www.cesnet.cz">www.cesnet.cz</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <div class="bigbox">
      	<div id="europeancommission" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://ec.europa.eu/research/fp7/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/ecflag.jpg"/><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/FP7.jpg"/></a>
            
          </div>
          <div class="description">
            <h1>European Commission</h1>
            <p>The European Commission's FP7 is the short name for the Seventh Framework Programme for Research and Technological Development. This is the EU's main instrument for funding research in Europe and it will run from 2007-2013. FP7 is also designed to respond to Europe's employment needs, competitiveness and quality of life.</p>
            <p>For more information, visit: <a href="http://ec.europa.eu/research/fp7/">http://ec.europa.eu/research/fp7/</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <div class="bigbox">
      	<div id="accessict" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.access-ict.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/accessict.jpg"/></a><br /><br />
                       
          </div>
          <div class="description">
            <h1>ACCESS ICT</h1>
            <p>&nbsp;</p>
            <p>For more information, visit: <a href="http://www.access-ict.com/">www.access-ict.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <div class="bigbox">
      	<div id="inveatech" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.invea-tech.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/inveatech.jpg"/></a><br /><br />
                       
          </div>
          <div class="description">
            <h1>Invea Tech</h1>
            <p>&nbsp;</p>
            <p>For more information, visit: <a href="http://www.invea-tech.com/">www.invea-tech.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
       <div class="bigbox">
      	<div id="av" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.avmedia.cz/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/av.jpg"/></a><br /><br />
                       
          </div>
          <div class="description">
            <h1>AV MEDIA, a.s.</h1>
            <p>AV MEDIA was founded in 1992, becoming the current number one in the field of presentation, projection and audiovisual technology. The service portfolio includes sale and lease of presentation technology, audiovisual system integration and other services, providing top technology standard.
You will find the company products in conference and meeting rooms, non-stop dispatch control stations, classrooms, university lecture halls, training rooms, special simulation and 3D applications, trade fairs, and many other places.
The company represents the following brands in the Czech Republic: ASK Proxima, Cisco, CUE, Epson, Christie, InFocus, Mitsubishi, Panasonic, Projecta, Projectiondesign, SMART Technologies, Synelec, Tandberg and others.
AV MEDIA is a holder of the ISO 9001: 2000 certificate and a member of the following professional bodies: Association of System AV Integration Dealers (ASAVI), InfoComm International, AV Global Alliance and Prague Convention Bureau (PAKT).
AV MEDIA, a.s. has qualified as an InfoComm International Silver Certified AudioVisual Solutions Provider (CAVSP).</p>
            <p>For more information, visit: <a href="http://www.avmedia.cz/">www.avmedia.cz</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <div class="bigbox">
      	<div id="ics" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.intercomsystems.cz/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/ics.jpg"/></a><br /><br />
                       
          </div>
          <div class="description">
            <h1>INTERCOM SYSTEMS a.s.</h1>
            <p>The company INTERCOM SYSTEMS a. s. has been active in the field of telecommunication and network technologies since 1991. The main subject of its activity is design and implementation of computer networks and data centers including supplies of active network equipment and providing high-value-added services. Activities of the firm include pre-sales consultations, network topology designs, project documentation elaborations, sales, installations, configurations, trainings and all activities bound to warranty and post-warranty service. In recent years, the company has specialized in network security solutions, wireless networks, unified communications and data centers.

In the network area, INTERCOM SYSTEMS has in the long term focused on products of Cisco Systems, Inc., a world leader in manufacturing products for data and multimedia communications. Intercom Systems has been a business partner of this manufacturer since 1991 (making it the first partner of Cisco Systems, Inc. in the Czech market); currently it is a Silver Partner and can boast Cisco’s full support thanks to the high technological level of its provided solutions and services. Intercom Systems is also a partner of HP, VMWare, EMC2 and NetApp.

Among the most valuable customers of INTERCOM SYSTEMS can be found such firms and institutions as Cesnet, Institute of Chemical Technology Prague, University of West Bohemia, Ministry of the Interior, Senate of Parliament, Ministry of Industry and Trade, Ministry for Regional Development, National Library, Škoda Auto, Prague Public Transport Company, Dial Telecom, Centronet and many others.</p>
            <p>For more information, visit: <a href="http://www.intercomsystems.cz/">www.intercomsystems.cz</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <div class="bigbox">
      	<div id="msmt" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.msmt.cz/index.php?lang=2"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/msmt.jpg"/></a><br /><br />
                       
          </div>
          <div class="description">
            <h1>Ministry of Education, Youth and Sports</h1>
            <p>&nbsp;</p>
            <p>For more information, visit: <a href="http://www.msmt.cz/index.php?lang=2">www.msmt.cz</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <div class="bigbox">
      	<div id="ctu" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://www.cvut.cz/en?set_language=en"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/ctu.jpg"/></a><br /><br />
                       
          </div>
          <div class="description">
            <h1>Czech Technical University in Prague</h1>
            <h2>Media Partner of TNC2011</h2>
            <p>Our mission is to coordinate, integrate and develop the university’s activities in the area of Information and Communication Technology. We are a partner for each of the faculties and participate in providing mainly centralised services aimed at developing and operating control components and applications. Our portfolio also consists of audio/video and multimedia services and webdesign.</p>
            <p>For more information, visit: <a href="http://www.cvut.cz/en?set_language=en">www.cvut.cz</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
            
      <div class="bigbox">
      	<div id="mashable" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://mashable.com/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/mashable.jpg"/></a>
            
          </div>
          <div class="description">
            <h1>Mashable</h1>
            <h2>Media Partner of TNC2011</h2>
            <p>&nbsp;</p>
            <p>For more information, visit: <a href="http://mashable.com/">www.mashable.com</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      
      <div class="bigbox">
      	<div id="idg" class="body">
          <div class="img_name">
            <a title="Click to visit the website" href="http://idg.cz/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/idg.jpg"/></a><br /><br />
            <a title="Click to visit the website" href="http://www.cw.cz/"><img alt="click to visit the website" src="/includes/tnc2011/gfx/logos/cw.jpg"/></a>
            
          </div>
          <div class="description">
            <h1>IDG</h1>
            <h2>Media Partner of TNC2011</h2>
            <p>IDG is the world´s leading technology media, events and research company. Computerworld is IDG´s flagship brand, launched in the U.S. in 1967 and in the Czech Republic in 1990. It´s the leading source of technology news and information for IT influencers worldwide, providing peer perspective, IT leadership and business results.
On the Czech and Slovak market Computerworld is the only biweekly magazine focusing on the B2B sphere of information and communication technologies. </p>
            <p>For more information, visit: <a href="http://idg.cz/">idg.cz</a> and <a href="http://www.cw.cz/">www.cw.cz</a>.</p>
          </div>
          <div class="clearer"></div>
      	</div>
        <div class="closer"></div>
      </div>
      */ ?>
      
        
    </div><!--end content-->
    
    <div id="sidebar">
      
      <div class="box">
      	<div class="body">
           <h1>Sponsors TNC2012</h1>
           <p>For more information about sponsorship opportunities, please contact:</p>
           <p><a href="mailto:horvath@terena.org?subject=TNC%202012" title="Contact Gyöngyi Horváth">Gyöngyi Horváth</a><br />
					The TNC2012 Sponsor Package can be downloaded and printed:<a href="/includes/tnc2011/documents/sponsorbrochure.pdf">
	    	 	<img alt="tnc2012 sponsor" src="/includes/tnc2011/gfx/sponsorbrochure.jpg" />
	    	 	</a></p>
	    	 	
	      </div><!--end box body-->
        <div class="closer"></div>
    	</div><!--end box-->  
          <h2>List of TNC2012 sponsors</h2>
          
          <ul class="blockmenu">
          <li><i><a title="template" href="#template">Your company name</a></i></li>
          
          	<? /*<li><a title="Telefonica" href="#telefonica">Telefonica</a></li>
          	<li><a title="Telindus" href="#telindus">Telindus</a></li>
             	 
          	 <li><a title="Globalcrossing" href="#globalcrossing">Global Crossing</a></li>
          <li><a title="HP" href="#hp">HP</a></li>
             <li><a title="NSN" href="#nsn">Nokia Siemens Networks</a></li>
             <li><a title="Cisco" href="#cisco">Cisco</a></li>
             <li><a title="Huawei" href="#huawei">Huawei</a></li>
             <li><a title="Adva" href="#advaoptical">Adva </a></li>
             <li><a title="Juniper" href="#juniper">Juniper Networks</a></li>
             <li><a title="RIPE NCC" href="#ripe">RIPE NCC</a></li>
             <li><a title="Vidyo" href="#vidyo">Vidyo</a></li>
             <li><a title="Comodo" href="#comodo">Comodo</a></li>
             <li><a title="Extreme Networks" href="#extreme">Extreme Networks</a></li>
             <li><a title="Custom Connect" href="#customconnect">Custom Connect</a></li>
             <li><a title="Ciena" href="#ciena">Ciena</a></li>
             <li><a title="Infinera" href="#infinera">Infinera</a></li>
             <li><a title="Level 3" href="#level3">Level 3</a></li>
             <li><a title="CESNET" href="#cesnet">CESNET</a></li>
             <li><a title="European Commission" href="#europeancommission">European Commission</a></li>
             <li><a title="Access ICT" href="#accessict">Access ICT</a></li>
             <li><a title="Invea Tech" href="#inveatech">Invea-Tech</a></li>
             <li><a title="AV Media" href="#av">AV Media</a></li>
             <li><a title="ICS" href="#ics">Intercom Systems</a></li>
             <li><a title="CTU" href="#ctu">CTU</a></li>
             <li><a title="MSMT" href="#msmt">MSMT</a></li>
             <li><a title="Mashable" href="#mashable">Mashable (media partner)</a></li>
             <li><a title="IDG" href="#idg">IDG (media partner)</a></li>
             */ ?>
             
             <? /*<li><a title="NLnet" href="#nlnet">NLnet</a></li>
             <li><a title="Tata" href="#tata">Tata Communications</a></li>
             <li><a title="Skaidula" href="#skaidula">Skaidula</a></li>
             <? /*<li><a title="Ekinops" href="#ekinops">Ekinops</a></li>
             <li><a title="Infinera" href="#infinera">Infinera</a></li>
             <li><a title="RedIRIS" href="#rediris">RedIRIS</a></li>*/ ?>
             <? /*<li><a title="LITNET" href="#litnet">LITNET</a></li>*/ ?>
          </ul>
          
    </div>
		<div class="clearer"></div>
