<!DOCTYPE html>
<?= $this->doctype(); ?>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="favicon.ico">
	<link href="/includes/responsive/css/bootstrap.min.css" rel="stylesheet">
	<link href="/includes/responsive/css/jumbotron.css" rel="stylesheet">
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	<?= $this->headTitle() ?>
	<?= $this->headLink() ?>
	<?= $this->headMeta() ?>
	<?= $this->headStyle() ?>
	<?= $this->headScript() ?>
	<script type="text/javascript" src="/js/terena.js?v=1"></script>
</head>
<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$controller = $request->getControllerName();
?>
<body>
	<nav class="navbar navbar-default">
	  <div class="container">
	    <div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/"><?= $this->conferenceInfo('name'); ?></a>
			</div>
	    <div id="navbar" class="navbar-collapse collapse">
	    	<ul class="nav navbar-nav navbar-right">
	  			<li><a href="/web/contacts">Contacts</a></li>
	  			<li><a href="/web/sponsors">Sponsors</a></li>
	  			<?php if ($this->authInfo()->isLoggedIn()): ?>
	  			<li><a href="<?=$this->url(array('controller' => 'user', 'action' => 'edit', 'id' => $this->authInfo('user_id')), 'gridactions')?>"
	  			title="<?= $this->translate('Manage account details'); ?>">Edit account</a></li>
	  			<li id="Logout"><a href="<?= $this->url(array('controller' => 'user', 'action' => 'logout'), 'main-module') ?>">Sign out</a></li>
	  			<? else: ?>
	  			<li id="Login"><a href="<?= $this->url(array('controller' => 'user', 'action' => 'login'), 'main-module') ?>">Sign in</a></li>
	  			<? endif; ?>
	  		</ul>
			</div><!--/.navbar-collapse -->
		</div><!--/.container -->
	</nav>

	<div class="jumbotron">
	  <div class="container"></div>
	</div>

	<div class="container"><!-- content -->
	
		<nav id="mainnav" class="navbar navbar-inverse" >
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main" aria-expanded="false" aria-controls="navbar">
	    	    <span class="sr-only">Toggle navigation</span>
	    	    <span class="icon-bar"></span>
	    	    <span class="icon-bar"></span>
	    	    <span class="icon-bar"></span>
	    	  </button>			
				</div>
				<div id="navbar-main" class="navbar-collapse collapse">
					<?= $this->navigation()->menu()->SetUlClass('nav navbar-nav')->setMaxDepth(0); ?>
				</div>
			</div>
		</nav>
		<? if ($controller != 'index'): ?>
		<nav id="subnav" class="navbar navbar-default">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-sub" aria-expanded="false" aria-controls="navbar">
	    	    <span class="sr-only">Toggle navigation</span>
	    	    <span class="icon-bar"></span>
	    	    <span class="icon-bar"></span>
	    	    <span class="icon-bar"></span>
	    	  </button>			
				</div>
				<div id="navbar-sub" class="navbar-collapse collapse">
					<?=	$this->navigation()->menu()->setMinDepth(1)->setRenderParents(false)->SetUlClass('nav navbar-nav')->setOnlyActiveBranch(true) ?>
				</div>
			</div>		
		</nav>
		<? endif; ?>

		<div class="row">
			<div id="newsticker" class="col-md-12">
				<div class="well well-sm">
				  <span id="section">Announcements</span> | <span class="news_text">&nbsp;</span>
				  <a href="/web/media/announcements" class="pull-right"><img alt="placeholder" src="/includes/<?= $this->conferenceInfo('abbreviation'); ?>/gfx/icons/next.gif" id="nextimg" /></a>
				</div>
			</div>
		</div>

    <?= $this->layout()->content; ?>
		<hr>
		</div>
		<footer>
			<p>Networks <strong>&middot;</strong> Services <strong>&middot;</strong> People | <a href="/web/participate/conduct">Code of Conduct</a> | <a href="https://www.terena.org/p3p">Privacy Policy</a></p>
		</footer>
	</div><!-- /container -->

	<!-- Bootstrap core JavaScript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="/includes/responsive/js/bootstrap.min.js"></script>
</body>
</html>