<div id="r<?= $this->presentation_id ?>" class="rate_widget">
<div class="ratings_stars star_1" id="fb_<?= $this->presentation_id ?>_1"></div>
<div class="ratings_stars star_2" id="fb_<?= $this->presentation_id ?>_2"></div>
<div class="ratings_stars star_3" id="fb_<?= $this->presentation_id ?>_3"></div>
<div class="ratings_stars star_4" id="fb_<?= $this->presentation_id ?>_4"></div>
<div class="ratings_stars star_5" id="fb_<?= $this->presentation_id ?>_5"></div>
<div class="ratings_stars delete" id="fb_<?= $this->presentation_id ?>_0"></div>
</div>