      <div class="widebox">
				<div class="body">
          <h1>Tours - by GUARANT International</h1>
          <p>Special tours have been arranged by GUARANT International exclusively for participants and accompanying persons of the TERENA Networking Conference 2011. All tours will leave from and return to the Clarion Congress Hotel Prague (main entrance). Booking in advance is recommended, on-site availability cannot be guaranteed. A minimum number of participants is 13. The deadline for application is May 11, 2011.</p>

  		  <h1 class="legend">Local Conference Organiser</h1>
          <p>All questions and correspondence about tour bookings should be sent to the local conference organiser:</p>
          <p><strong>GUARANT International</strong><br/>
            Opletalova 22<br />
			110 00 Prague 1,<br/>
          Czech Republic<br/>
          T:+420 284 001 444<br/>
          F:+420 284 001 448<br/>
          Email:<a href="mailto:terena2011@guarant.cz">terena2011@guarant.cz</a><br/>
          Url:<a class="url" href="http://www.guarant.com/">www.guarant.com</a></p>

          <h2>How to book a tour</h2>
          
          <p class="notice"><a href="https://secure.guarant.cz/terena2011/">BOOK A TOUR!</a></p>
          
          <p>Please note that the on-line Tours Form is only accessible with a password. Simply fill in the Personal Data Form and a password will be sent to you. Your password is the same as for the on-line accommodation Form.</p>
          
          <p>GUARANT International, the Local Conference Organiser reserves the right to cancel the tour for which a minimum number of participants have not registered. In this case another tour will be offered or a refund will be paid after the conference.</p>
          
          <h2>Meeting point</h2>
          <p>Clarion Congress Hotel Prague, Main entrance. Please be at the meeting point 15 minutes before the departure time.</p>
          
          <h2>Cancellation fee</h2>
          <p>Please inform GUARANT International of any amendments or cancellations in writing by fax (+420 284 001 448) or via e-mail: <a href="mailto:terena2011@guarant.cz">terena2011@guarant.cz</a>. Telephone amendments will not be accepted. The appropriate refunds will be made during or after the Conference.</p> 

			<p>The following cancellation conditions apply to the cancellation of tours:<br />
			2 days before a tour starts - no cancellation fee <br />
Less than 2 days - 100 % cancellation fee</p>

				</div>
        <div class="closer"></div>
      </div><!--end widebox-->

     <div class="clearer"></div>

      <div class="col">
      <div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>EVENING RIVER CRUISE WITH DINNER</h1>
                <p>4 hours</p>
                
               </div>
              <img src="/includes/tnc2011/gfx/photos/venue/river.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->
            <h1>EVENING RIVER CRUISE WITH DINNER</h1>
            <p>Have you got an evening off in Prague? Accept our invitation for an evening river cruise along the Vltava. We drive you to the boat where you will spend 3 pleasant hours. Cold and warm buffet as dinner is included. You are accompanied by our guide and you also listen to live music aboard. The best thing is to see Prague monuments from again a different perspective! After the boat trip we drive you back to your hotel.</p>
            <h2>Price</h2>
			<p>EUR 34 per person</p>  
            <h2>Meeting point:</h2>
            <p>Clarion Congress, main entrance, ground floor, next to the fountain</p>
            <h2>Departure:</h2>
            <p>Tuesday, 17 May 2011 at 18:15 (leaving at 18:30)</p>
            <h2>Tour end:</h2>
			<p>Clarion Congress</p>
			<h2>Price includes:</h2>
			<p>English speaking guide, 2 transfers, three hours boat trip with buffet dinner and welcome drink</p>              
					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->

             
            </div>  <!--end col-->


      <div class="col2">

        <div class="box">
        	<div class="body">
            <div class="hotelintro">
              <div class="hotelmeta">
                <h1>FOLKLORE EVENING</h1>
                <p>3,5 hours</p>
                
               </div>
              <img src="/includes/tnc2011/gfx/photos/venue/folk.jpg" alt="hotel photo"/>
            </div><!--hotelintro-->
            <h1>FOLKLORE EVENING</h1>
            <p>TCzech folklore music and dances are so melodic, beautiful and full of energy that it has been a great inspiration for whole generations of artists. Our folklore evening is the best choice for everybody who wants to spend an enjoyable evening in a traditional Czech restaurant, who would like to learn something new and have good dinner and good drinks. During this evening programme our guests can also sing and dance. On your way there by bus our guide will speak about the illuminated monuments you pass and about Czech history and traditions. In short you will spend an unforgettable evening! <br />INCLUDING DINNER AND DRINKS WITHOUT LIMIT</p>
            <h2>Price</h2>
			<p>EUR 59 per person</p>  
            <h2>Meeting point:</h2>
            <p>Clarion Congress, main entrance, ground floor, next to the fountain</p>
            <h2>Departure:</h2>
            <p>Tuesday, 17 May 2011 at 18:45 (leaving at 19:00)</p>
            <h2>Tour end:</h2>
			<p>Clarion Congress</p>
			<h2>Price includes:</h2>
			<p>English speaking guide, 2 transfers, dinner, drinks without limit</p>              
					</div><!--end box body-->
          <div class="closer"></div>
        </div><!--end box-->

	  </div><!--end col-->

      <div class="col">






		</div>  <!--end col-->


      <div class="clearer"></div>
