  <div class="vcard">

  <h1><abbr class="geo" title="52.367238; 4.889389"><span class="fn org">TERENA Secretariat</span></abbr></h1>
  <div class="adr">
    <span class="street-address">Singel 468 D</span><br />
    <span class="locality">Amsterdam</span>,
    <span class="postal-code">1017 AW</span>
    <div class="country-name">The Netherlands</div>
  </div>
  <div class="tel">
    <abbr class="type" title="voice">T:</abbr>
    <span class="value">+31 20 530 44 88</span>
             </div>
  <div class="em">Email:
    <span class="email"><a href="mailto:secretariat@terena.org">secretariat@terena.org</a></span>
  </div>
  <div>WWW:
    <a class="url" href="http://www.terena.org/">http://www.terena.org</a>
  </div>
</div>