    <div class="bigbox">
        <div class="body">
            <h1>Registration</h1>
            <p>Limited number of on site registration is available from Monday, 16 May 2011 to Thursday, 19 May 2011.</p>
            
            <? /*<p>Registration for the TERENA Networking Conference 2011 commences on 21 February 2011.</p>*/ ?>
            <? /*<p>Please register for the TERENA Networking Conference 2011 online or with the downloadable <a href="/files/tnc2011_registrationform.pdf" title="registration form">registration form</a> (pdf). If you use the pdf registration form, please follow the instructions for payment of fees carefully and return the form by fax to TERENA. You will receive an acknowledgement by e-mail.</p>
            <p>Note that payment by credit card via faxed form is not possible in many cases due to increased security regulations. If you want to pay by credit card, online registration is strongly encouraged.<br />

Once you have registered, you will receive an acknowledgement by email.</p>

        <h2 id="a_online">Online Registration</h2>
        <div>
        <p>Register online using our secure server. If you pay by credit card you will automatically receive a receipt by email. If you choose to pay by bank transfer or bank draft (Bankers&rsquo; Guaranteed Cheque) you will automatically receive an invoice.</p>
        <h2>Visa requirements</h2>
        <p>Those requiring supporting documentation in order to obtain a visa should contact GUARANT International directly <a href="mailto:terena2011@guarant.cz?subject=TNC2011%20Visa%20request">terena2011@guarant.cz</a></p>
        <p>Please be aware that a letter of invitation does not imply any financial support. You will still be subject to the normal registration fee detailed above. Registration to the conference is necessary. The payment and accommodation booking must be made prior to requesting an invitation letter.</p>
        
        <p>Details of visa requirements for entry into the Czech Republic can be found at the Czech of Foreign Affairs&rsquo; website:
<a href="http://www.mzv.cz/jnp/en/index.html">http://www.mzv.cz/jnp/en/index.html</a></p>
        </div>

		<h2 id="a_student">CALL FOR SPONSORED STUDENT POSTER PLACES</h2>
		<i>Sponsored by Cisco Systems</i>
		<div>
		<p>There is a limited number of sponsored registration places for bona-fide students from relevant fields. Eligible students will receive free admission to the conference and are expected to present a poster at the conference and it will also be posted online. The best student poster will receive an award at the end of the conference.</p>
<p>Students are encouraged to apply by submitting a short poster abstract (100 to 250 words) on any of the subjects relevant to the spirit and objectives of the conference. Applications should be sent to <a href="mailto:tnc2011@terena.org?subject=TNC2011%20Student%20Poster">tnc2011@terena.org</a> with the subject "TNC2011 Student Poster" by 30 April 2011.</p>
    <p>Note that TERENA does not offer any financial assistance for travel or accommodation costs.</p>
    <h2 id="a_poster">CALL FOR POSTERS</h2>

<p>In the last two years, several TNC participants have created <a href="http://tnc2010.terena.org/schedule/posters/">high quality poster presentations</a>. An effective poster presentation is not just a standard research paper stuck to a board. It should summarise your work with graphs and images to tell the story and should use text more sparingly. Featuring a poster at TNC will serve as an excellent advertisement for your work, and can act as a great conversation starter with TNC participants.</p>

<p>In general, poster presentations are less formal than regular presentations, are more interactive and can provoke various points of view. Selected posters will be displayed in an area close to the parallel sessions and on the conference website. Proposals for poster presentations can be submitted by sending a short abstract (100 to 250 words) to <a href="mailto:tnc2011@terena.org?subject=TNC2011%20Poster">tnc2011@terena.org</a> with the subject "TNC2011 Poster" by 30 April 2011. The authors of the accepted posters will be asked to send the pdf of the poster by 6 May 2011. Poster size: up to size A1 - 594mm X 841mm (portrait or landscape).</p>

<p>The abstracts of accepted posters will be included in a directory of poster presentations in the conference bags.</p>

    </div>
    
    <h2 id="a_lightning">GIVE A LIGHTNING TALK</h2>
<div>
<p>Lightning talks are five-minute presentations focusing on one key point; this can be an idea, a successful project, a cautionary story, a collaboration invitation, a quick tip or a demonstration.<br />

Use this time wisely to present the pertinent message of the subject matter without the need for background history, the problem space or a business-case justification.<br />

Lightning talks are an excellent opportunity for first-time speakers.<br />

We will have sixteen lightning talks at TNC2011 on 19 May 2011 from 9:00 - 10:30.<br />
Email <a href="mailto:lightning-talks@terena.org?subject=TNC2011%20Lightning%20Talk">lightning-talks@terena.org</a> including your bio, a proposed title and a short description of your talk. The deadline for submissions is 18 April 2011.</p>
</div>*/ ?>


        </div><!--end body-->
      <div class="closer"></div>
    </div><!--end bigbox-->

    <div class="bigbox">
		<div class="body">
            <h1>Methods of payment</h1>
            <p>If you have questions or concerns about payments, please contact TERENA <a href="mailto:bookkeeper@terena.org?subject=TNC2011%20payment%20method">bookkeeper@terena.org</a> to discuss your requirements.</p>

            <p>Payments will be accepted until 6 May 2011 by bank transfer or bank draft (Bankers&rsquo; Guaranteed Cheque) and by credit card. After these dates, only desk registration (in Prague) is available <? /*(600 euro)*/ ?>.</p>

            <p>Payments for conference registration and accompanying person&rsquo;s may be made using the following methods:</p>

            <h2>Credit card</h2>
            <p>Please write the credit card numbers, CVC code, the expiry date and the amount to be debited on the registration form.
            Please include the name of the credit card holder as it is written on the card.</p>

            <h2>Bank transfer</h2>
            <p>Please send a bank draft (Bankers&rsquo; Guaranteed Cheque) or bank transfer in euro, net all bank charges, payable to:</p>

            <p>TERENA, Singel 468 D, 1017 AW Amsterdam, The Netherlands<br />
            ABN-AMRO Bank<br />
            Dam<br />
            Amsterdam, The Netherlands<br /><br />

            Account number: 62 63 49 028<br />
            IBAN: NL07ABNA0626349028<br />
            BIC/SWIFT: ABNANL2A<br /></p>

            <p>Please enclose a copy of your completed registration form.</p>

            <p>If your company/institution requires an invoice in advance or an invoice for several participants, please contact TERENA to give us details of the required invoice.</p>

            <h2>Desk registration</h2>
            <p>For on-site registration in Prague (600 euro), payment may be made by credit card, by bank draft (Bankers&rsquo; Guaranteed Cheque) or in cash.</p>

        </div><!--end body-->
		<div class="closer"></div>
	</div><!--end bigbox-->


    </div>
    
    
    <div id="sidebar">
    
	<div class="box">
		<div class="body">
			<? /*<h1>Immediately go to:</h1>
	       	<p class="notice"><a href="https://www.terena.org/webshop/?id=57" class="left">Register Online</a><a href="#a_online" class="right">?</a></p>
	       	<p class="notice"><a href="mailto:tnc2011@terena.org?subject=TNC2011%20Student%20Poster">Submit Student Poster</a><a href="#a_student" class="right">?</a></p>
	       	<p class="notice"><a href="mailto:tnc2011@terena.org?subject=TNC2011%20Poster">Submit Poster</a><a href="#a_poster" class="right help">?</a></p>
	       	<p class="notice"><a href="mailto:lightning-talks@terena.org?subject=TNC2011%20Lightning%20Talk">Lightning Talks</a><a href="#a_lightning" class="right">?</a></p>*/ ?>
	       	<h1>On site registration fees</h1>
	        <table class="tnc" summary="Conference registration fee">
			<tr>
			<td>Whole week registration</td>
			<td class="amount">&euro; 600*</td>
			</tr>
			<tr>
			<td>Monday registration</td>
			<td class="amount">&euro; 100*</td>
			</tr>
			<tr>
			<td>Tuesday registration</td>
			<td class="amount">&euro; 200*</td>
			</tr>
			<tr>
			<td>Wednesday registration</td>
			<td class="amount">&euro; 200*</td>
			</tr>
			<tr>
			<td>Thursday registration</td>
			<td class="amount">&euro; 100*</td>
			</tr>
			<tr>
			<td>Accompanying person's registration</td>
			<td class="amount">&euro; 100*</td>
			</tr>
			<tr>
			<td>Additional Gala dinner ticket</td>
			<td class="amount">&euro; 65</td>
			</tr>
            </table>
	     	<p>The conference registration fee includes: </p>
	        <ol>
	            <li>access to all conference sessions</li>
	            <li>all conference materials (programme, conference bag, stationery and related materials)</li>
	            <li>Opening Reception (Monday 16 May 2011)</li>
	            <li>Gala Evening (Wednesday 18 May 2011)</li>
	            <li>lunches (on 16 - 18 May 2011)</li>
	            <li>refreshment breaks</li>
	        </ol>

	        <p>The accompanying person&rsquo;s registration fee includes: </p>
	        <ol>
	        	<li>Opening Reception (Monday 16 May 2011)</li>
	        	<li>Gala Evening (Wednesday 18 May 2011)</li>
	        	<li>Public transport pass (valid for 5 days)</li>
	        </ol>
	        <p>*(inclusive 20% VAT)</p>
		</div><!--end body div-->
  		<div class="closer"></div>
  	</div><!--end box-->


    	<div class="box">
        <div class="body">
          <h1>Poster specifications</h1>
          <p>Poster size: up to size A1 - 594mm X 841mm (portrait or landscape).</p>
          <p>Format to be submitted for the website: PDF (by 6 May 2011)</p>
          <p>The selected posters may be brought to the conference on Monday 16 May and delivered to the TERENA Conference Secretariat at the Clarion Congress Hotel or sent by post to:</p>
          <div class="vcard">
              <h2><span class="fn org">GUARANT International</span></h2>
              <div class="adr">
                <span class="street-address">Opletalova 22</span><br />
                <span class="locality">Prague 1</span>,
                <span class="postal-code">110 00</span>
                <div class="country-name">Czech Republic</div>
              </div>
            </div><!--end vcard-->
          <p>Attention: Veronika Brejchova</p>
        </div><!--box body-->
      	<div class="closer"></div>
			</div>


	<div class="box"> 	
		<div class="body">
			<h2>Accommodation</h2>
	        <p>Please consult the <a href="/webdemo/venue/hotels">hotel</a> section for further information about conference accommodation. The prices listed include all local taxes and breakfast. These costs are not included in the registration fee.</p>
		</div>
  		<div class="closer"></div>
  	</div><!--end box-->

	
	<div class="box"> 	
		<div class="body">	
			<h2>VAT information</h2>
	        <p>*20% VAT is included in the registration fees.</p>
			<h2>Terms and conditions</h2>
	        <p>Please check the <a href="https://www.terena.org/webshop/terms.html">terms and conditions</a> of the TERENA registration.</p>
		</div>
		<div class="closer"></div>
  	</div><!--end box-->
	
	
	
	
	
<div class="clearer"></div>




