
	<div class="bigbox">
  	<div class="body">
      <h1>CALL FOR SPONSORED STUDENT POSTER PLACES</h1>
      <i>Sponsored by Cisco Systems</i>
      <? /*<p>Students can apply to attend the conference free of charge: a limited number of sponsored registration places will be available for bona fide postgraduate students from relevant fields.<br />
Call for Student contribution will be announced in January 2011, follow the news and announcements.</p>*/ ?>
      <p><a href="/includes/tnc2011/gfx/photos/">
	    	 	<img alt="tnc2011 students" src="/includes/tnc2011/gfx/photos/studentposter.png" />
	    	 	</a></p>
	Applications should be sent to <a href="mailto:tnc2011@terena.org?subject=TNC2011%20Student%20Poster">tnc2011@terena.org</a> with the subject &lsquo;TNC2011 Student Poster&lsquo; by <br /><strong>30 April 2011</strong>.</p>
	<p>A subpanel of the Program Committee will select the best papers for acceptance and inform all submitting students before the end of the early registration.</p>
	</div><!--end body-->
    <div class="closer"></div>
	</div><!--end bigbox-->
</div><!--end content-->

<div id="sidebar">
	<div class="box">
  	<div class="body">
  	<h1>Important Dates</h1>
    	<table class="tnc" summary="important dates for the TERENA Networking Conference 2011">
          <? /*<tr class="odd">
            <td>Extended abstracts</td>
            <td><strong>30 November 2010</strong></td>
	          </tr>
          <tr>
            <td>Notification of acceptance</td>
            <td>21 January 2011</td>
          </tr>*/ ?>
          <tr class="odd">
          	<td>Registration commences:</td><td>21 February 2011</td>
          </tr>
          <tr>
          	<td>Submission of full papers:</td><td>15 April 2011</td>
          </tr>
          <tr class="odd">
          	<td>Submission of posters:</td><td>30 April 2011</td>
          </tr>
          <tr class="odd">
          	<td>Submission of poster pdf:</td><td>6 May 2011</td>
          </tr>
          <tr>
          	<td>Presentation slides<sup><strong>*</strong></sup>:</td><td>1 May 2011</td>
          </tr>
          <tr class="odd">
          	<td>Conference:</td><td>16 - 19 May 2011</td>
          </tr>
      </table>
      <p>* Please note that presentation slides may be updated by the speaker up to 30 minutes before the presentation.</p>
      
      
         
    </div><!--end body-->
    
    
    
    <div class="closer"></div>
   </div><!--end box -->
   