<h1>Users</h1>
<a href="<?= $this->url(array('controller'=>'user', 'action'=>'new'), 'main-module') ?>" title="invite a new user">Invite</a>
<?
function globFilter($input)
{
	return !isset($input['hidden']);
}
$columns = array_filter($this->grid['cols'], 'globFilter');
?>

<?		
$searchField = $this->formText('search',
	$this->searchString,
	array("onchange" => "this.form.submit();", "class" => "medium", "title" => "search user")
);
$resetButton = $this->formSubmit('reset_search',
	'reset',
	array("onclick" => "this.form.submit();", "style" => 'width:100px;')
);
?>
<form id="filterform" action="<?= $this->url() ?>" method="post"><p><?= $searchField ?> <?= $resetButton ?></p></form>

<? if ($this->grid['rows']->count() !== 0): ?>
<? if ( ($this->grid['rows'] instanceof Zend_Paginator) && ($this->grid['rows']->getTotalItemCount() > $this->grid['rows']->getItemCountPerPage()) ): ?>
<?= $this->paginationControl($this->grid['rows'], 'Sliding', '_paginator.phtml', array('route_name' => 'grid')); ?>
<? endif; ?>
<table class="table grid" cellspacing="0" summary="Users">
<thead>
<tr>
<th style="width:3px;padding:0;margin:0;"></th>
<? foreach (array_keys($columns) as $col):  ?>
<? $dir = ($this->grid['params']['dir'] === 'desc') ? 'asc' : 'desc' ?>
<th>
	<? if ($columns[$col]['sortable'] === true): ?>
	<a href="<?= $this->url(array('order' => $col, 'dir' => $dir), 'grid') ?>"><?= $columns[$col]['label'] ?></a>
	<? else: ?>
	<?= $columns[$col]['label'] ?>
	<? endif; ?>
	<? if ($columns[$col]['field'] === $this->grid['params']['order']): ?>
	<img class="" src="/includes/core/gfx/icons/sort_<?=$dir?>.gif" alt="sort icon" />
	<? endif; ?>
</th>
<? endforeach; ?>
<? if ($this->authInfo()->isAdmin() ): ?>
<th>Roles</th>
<th style="width:3px;padding:0;margin:0;">A</th>
<? endif; ?>
</tr>
</thead>
<tbody>
<? foreach ($this->grid['rows'] as $item): ?>
	<tr class="collapsible <?= $this->cycle(array('odd', 'even'))->next() ?>">
	<td rowspan="1" style="<? if ($item['invite']): ?>background:green;<? endif; ?>padding:0;margin:0;width:3px;"></td>	
  	<? foreach (array_keys($columns) as $col):  ?>
  		<td>
  		<?
  		// apply modifiers
		$output='';
  		if ( isset($columns[$col]['modifier']) ) {
  			if ($columns[$col]['modifier'] instanceof Closure) {
				$output = $columns[$col]['modifier']($item->$col);
  			} else {
  				$output = call_user_func(array($this, $columns[$col]['modifier']), $item->$col);
  			}
  		} else {
  			$output = $item->$col;
  		}
		echo $output;
  		?>
  		</td>
  		
  	<? endforeach; ?>
  	
	<td><?= implode(", ", $item->getRoles(true)) ?></td>
  	<? if ($this->gridactions): ?>
  	<? $this->item = $item; ?>
  	<?= $this->render($this->gridactions) ?>
  	<? else: ?>
	<? if ($this->authInfo()->isAdmin() ): ?>
		<td>
		<a href="<?= $this->url(array('action' => 'edit', 'id' => $item->{$this->grid['primary']}), 'gridactions') ?>">edit</a> |
		<a href="<?= $this->url(array('action' => 'delete', 'id' => $item->{$this->grid['primary']}), 'gridactions') ?>">delete</a>
		</td>
	<? endif; ?>
  	<? endif; ?>
  	
	</tr>

	<tr class="extra <?= $this->cycle(array('odd', 'even'))->current() ?>">
	<td colspan="7">
	
	<!-- User information -->
	<dl class="userinfo">
	<dt>Identity</dt><dd>
	<?if($item['uid']):?>
		<?= $item['uid']?>
	<?else:?>
		Not yet known because user has not used activation link in the invitation e-mail
	<?endif;?></dd>
	<dt>Inserted at</dt><dd><?= $this->formatDate($item['inserted']) ?></dd>
	<dt>Method</dt><dd>
	<?if ($metadata = $item->getAuditData()):?>
		Invited as <?= '"' . $metadata['fname'] . ' ' . $metadata['lname'] .' <' . $metadata['email'] . '>"' ?>
	<?else:?>
		Self registered
	<?endif;?>
	</dd>
	</dl>
	<!-- end User information -->
	
	
	</td>
	</tr>
<? endforeach; ?>
</tbody>
</table>
<? endif; ?>
<? if ( ($this->grid['rows'] instanceof Zend_Paginator) && ($this->grid['rows']->getTotalItemCount() > $this->grid['rows']->getItemCountPerPage()) ): ?>
<?= $this->paginationControl($this->grid['rows'], 'Sliding', '_paginator.phtml', array('route_name' => 'grid')); ?>
<? endif; ?>