<?
/**
 * Contains all the view logic to render a grid.
 * This view expects the view variable $grid to be set
 * with the keys: 'rows', 'cols', 'primary', 'params'
 *
 * @fix replace hardcoded controller check for user with view helper
 * 			done - moved logic to custom Url view helper
 */

// filter out hidden columns
function globFilter($input)
{
	return !isset($input['hidden']);
}
$columns = array_filter($this->grid['cols'], 'globFilter');
?>
<? if ($this->grid['rows']->count() !== 0): ?>
<table class="grid table table-striped" cellspacing="0">
<thead>
<tr>
<? foreach (array_keys($columns) as $col):  ?>
<? $dir = ($this->grid['params']['dir'] === 'desc') ? 'asc' : 'desc' ?>
<th>
	<? if ($columns[$col]['sortable'] === true): ?>
	<a href="<?= $this->url(array('order' => $col, 'dir' => $dir), 'grid') ?>"><?= $columns[$col]['label'] ?></a>
	<? else: ?>
	<?= $columns[$col]['label'] ?>
	<? endif; ?>
	<? if ($columns[$col]['field'] === $this->grid['params']['order']): ?>
	<img class="" src="/includes/core/gfx/icons/sort_<?=$dir?>.gif" alt="sort icon" />
	<? endif; ?>
</th>
<? endforeach; ?>
<? if ($this->authInfo()->isAdmin() ): ?>
<th>Actions</th>
<? endif; ?>
</tr>
</thead>
<tbody>
<? foreach ($this->grid['rows'] as $item): ?>
  <tr class="<?= $this->cycle(array('odd', 'even'))->next() ?>">
  	<? foreach (array_keys($columns) as $col):  ?>
  		<td>
  		<?
  		// apply modifiers
  		if ( isset($columns[$col]['modifier']) ) {
  			if ($columns[$col]['modifier'] instanceof Closure) {
				echo $columns[$col]['modifier']($item->$col);
  			} else {
  				echo call_user_func(array($this, $columns[$col]['modifier']), $item->$col);
  			}
  		} else {
  			echo $item->$col;
  		}
  		?>
  		</td>
  	<? endforeach; ?>
  	<? if ($this->gridactions): ?>
  	<? $this->item = $item; ?>
  	<?= $this->render($this->gridactions) ?>
  	<? else: ?>
	<? if ($this->authInfo()->isAdmin() ): ?>
		<td>
		<a class="btn btn-default btn-xs" href="<?= $this->url(array('action' => 'edit', 'id' => $item->{$this->grid['primary']}), 'gridactions') ?>"><span class="glyphicon glyphicon-edit"></span></a>
		<a class="btn btn-default btn-xs" href="<?= $this->url(array('action' => 'delete', 'id' => $item->{$this->grid['primary']}), 'gridactions') ?>"><span class="glyphicon glyphicon-trash"></span></a>
		</td>
	<? endif; ?>
  	<? endif; ?>
  </tr>
<? endforeach; ?>
</tbody>
</table>
<? endif; ?>
<? if ( ($this->grid['rows'] instanceof Zend_Paginator) && ($this->grid['rows']->getTotalItemCount() > $this->grid['rows']->getItemCountPerPage()) ): ?>
<?= $this->paginationControl($this->grid['rows'], 'Sliding', '_paginator.phtml', array('route_name' => 'grid')); ?>
<? endif; ?>