<div class="widebox">
	<div class="body">
    <h1>Conference Topics</h1>
	
	
	
        <p>
            Extended abstracts (rather than full papers) are invited on all subjects relevant to the spirit and objectives of the conference: to present, discuss and learn about the latest developments in networking technology for the research and education community and their use by the community. The topics below are an indication of the planned scope of the conference, but are not meant to be restrictive.
        </p>
        
        <h2>Enabling Communities</h2>

        <table class="tnc" summary="Enabling Communities">
           <tbody>
          	<tr class="odd">
				<td>FUTURE NETWORKS</td>
            	<td>network technology, network management, control planes, virtual networks, future networks, bandwidth on demand, network architectures</td>
            </tr>
			
          	<tr class="odd">
				<td>COMMUNITIES &amp; IDENTITIES</td>
            	<td>federations, virtual organisation &amp; collaborations, e-science ecosystems, future research communities, future of the classroom, student communities, identity management, reshaping collaboration, teaching and learning communities, intelligent crowds</td>
            </tr>

          	<tr class="odd">
				<td>SUPPORTING COLLABORATION</td>
            	<td>real-time collaboration, access everywhere, collaboration beyond academic boundaries, social media</td>
            </tr>

          	<tr class="odd">
				<td>ADVANCED APPLICATIONS &amp; SERVICES</td>
            	<td>advanced media, location-aware services, Grids &amp; clouds, storage and databases, advanced &amp; demanding applications</td>
            </tr>

          	<tr class="odd">
				<td>DIGITAL LIFESTYLE</td>
            	<td>social considerations, privacy, security challenges, Internet governance, social media, digital natives</td>
            </tr>
			
			
             </tbody>
        </table>

<?
/*
    
        <p>
            Extended abstracts of about 1200 words (two A4 pages) must be submitted in English, the official language of the conference.
        </p>
*/

?>


    </div>   
  <div class="closer"></div>
</div>