<div class="widebox">
	<div class="body">
<h1>G&Eacute;ANT Associated Speakers</h1>
<h3>GN3 is co-funded by the European National Research and Education Networks (NRENs) and the European Union (EU) through the European Commission&rsquo;s Seventh Research and Development Framework Programme, The GN3 project started in April of 2009, following on from the GN2 project.</h3>

<p>Known simply as G&Eacute;ANT, GN3 is the third term of the successful G&Eacute;ANT network and project that lie at the heart of the EU&rsquo;s
e-Infrastructure strategy. The project will shape the Internet of the future through the pan-European G&Eacute;ANT network and a portfolio
of advanced services for the research and education community. G&Eacute;ANT also tackles the digital divide of research and education
networking across Europe and fosters technological research to assure Europe&rsquo;s role at the forefront of networking and e-Science.
In addition to the G&Eacute;ANT backbone network service, the G&Eacute;ANT project encompasses a number of Service, Joint Research Activities
and Networking Activities. As part of the Networking Activity on &quot;Joint Dissemination and Outreach&quot;, a G&Eacute;ANT workshop event is
attached to the annual TERENA conferences, and G&Eacute;ANT presentations included in the appropriate topic-oriented parallel
sessions throughout the conference programme.</p>

<p>TNC2011 programme will this year feature 12 speakers presenting on G&Eacute;ANT-related activities. They will cover a wide range of subjects covering the project&rsquo;s technology, service developments and other initiatives.</p>

<h3><img src="/includes/tnc2011/gfx/logos/geant.gif" alt="geant logo" /> GN3 Workshop presentations in the conference programme</h3>
<ul>

<li><a href="https://tnc2011.terena.org/core/presentation/74">Campus best practices</a><br />
Gunnar Boe, UNINETT</li>
<li><a href="https://tnc2011.terena.org/core/presentation/60">Trimming your AAI federation fit for eduGAIN technically</a><br />
Lukas Hammerle, SWITCH</li>
<li><a href="https://tnc2011.terena.org/core/presentation/86">GENUS: Virtualisation Service for G&Eacute;NT and European NRENs</a><br />
Reza Nejabati, University of Essex</li>
<li><a href="https://tnc2011.terena.org/core/presentation/14">The GEMBus Architecture and Core Components</a><br />
Diego Lopez, RedIRIS</li>
<li><a href="https://tnc2011.terena.org/core/presentation/49">Design and OAM&amp;P aspects of a DWDM system equipped with a 40Gb/s PM-QPSK</a><br />
Lars Lange Bjorn, NORDunet</li>
<li><a href="https://tnc2011.terena.org/core/presentation/80">Integration perfSONAR with the GEMBus as realization of the Enterprise Service Bus</a><br />
Krzysztof Dombek, PSNC</li>
<li><a href="https://tnc2011.terena.org/core/presentation/64">eduCONF Business Case: The quest for the Videoconference Community&rsquo;s needed services</a><br />
Rui Ribeiro, FCCN</li>
<li><a href="https://tnc2011.terena.org/core/presentation/4">Future networking</a><br />
Michael Enrico, DANTE</li>
<li><a href="https://tnc2011.terena.org/core/presentation/54">Network performance event management based upon the perfSONAR framework</a><br />
Robert Szuman, PSNC</li>
<li><a href="https://tnc2011.terena.org/core/presentation/84">perfSONAR NC - a NETCONF based perfSONAR implementation</a><br />
Arne Oslebo, UNINETT</li>
<li><a href="https://tnc2011.terena.org/core/presentation/73">Enhancing E2Emon monitoring with NML topology exchange</a><br />
Freek Dijkstra, SARA</li>
<li><a href="https://tnc2011.terena.org/core/presentation/26">Identity Provider Discovery Usability</a><br />
Andreas Akre Solberg, UNINETT</li>
<li><a href="https://tnc2011.terena.org/core/presentation/98">Emerging research networks in Albania and Kosovo - panel</a><br />
Valentino Cavalli, TERENA, Goran Skvarc, CARNet, Daniele Arena, CASPUR</li>
<li><a href="https://tnc2011.terena.org/core/presentation/53">Integration of Inter-Domain Reservation Systems with Other Composable Services</a><br />
Vasiliki Pouli, NTUA</li>
<li><a href="https://tnc2011.terena.org/core/presentation/129">Supporting Pan-European advanced applications - GÉANT Project liaison and support</a><br />
Domenico Vicinanza, DANTE</li>
</ul>
    </div>   
  <div class="closer"></div>
</div>