<h1>Mini Camera Instructions</h1>
<p><strong>Before you use the camera for the first time</strong> there are a couple of
things you should do:</p>
<p>
<ol>
	<li><strong>Charge the video camera:</strong>
		<ol>
			<li>Plug into a USB port. When the battery is charged the GREEN light will
not flash.</li>
			<li>For the first few times (~5) of using it, make sure it is fully
charged <strong>before</strong> you use the mini camera. This will help to extend the battery life.</li>
			<li>When the battery is low and needs recharging, the GREEN light will flash when its connected to the USB.</li>
			<li>When the battery is fully charged, the GREEN light will light steadily when its connected to the USB.</li>
		</ol>	
	</li>
	<li><strong>Alter the date stamp printed on the videos and pictures:</strong>
		<ol>
			<li>Turn the on/off switch to "on".<br/> (<strong>NOTE:</strong> You should <strong>not</strong> switch it to "off" again, if you do the date will reset to 2008 again and you will have to repeat the process).</li>
			<li>Plug the camera into a USB port, when it has been discovered, [link]download the file 'TAG.txt'[/link] onto the <strong>root</strong> of the camera disk (that's in the same directory as the one which has 'DCIM' in it, not in the DCIM directory itself)</li>
			<li>'Safely Remove' (eject) the camera</li>
			<li>Unplug the camera from the USB and wait a few seonds until only the GREEN light is lit.</li>
			<li>Hold down the large button for a few seconds until the RED light comes on, and release the large button. This turns the camera off.<br/> <strong>NOTE: DO NOT slide the 'on/off' switch to off, or you will lose the new date stamp!</strong> Don't worry, the battery will not run down with the slide switch set to 'on'.</li>
		</ol>
	</li>
	<li><strong>To use the video camera:</strong>
		<ol>
			<li>Make sure its fully charged and disconnected safely from the USB cable.</li>
			<li>Press the large button once. The GREEN light will come on, and then a
second later the RED light will flash (read the disk) and then go
off again.</li>
			<li>If the GREEN light flashes, it means that there is a problem with the
Mini-SD card. Check that it is properly inserted and try again.</li>
			<li>Press the large button once again and the RED light starts to flash. You
are now recording. If you can see the belt clip, then you are recording your own face!</li>
			<li>Press the large button once again to stop recording. The RED light will
flicker as the video is saved to the disk.</li>
			<li>Once the RED light has stopped flickering, press and hold down the
large button until the RED light comes on, and then release the large
button to switch the camera off. <strong>DO NOT slide the 'on/off' switch to
off, or you will lose the new date stamp!</strong></li>
		</ol>
	</li>
	<li><strong>To retrieve the videos from the camera:</strong>
		<ol>
			<li>Connect the camera to the USB port of your computer.</li>
			<li>If asked to scan the disk by your virus scanner, there is no reason
not to.</li>
			<li>When the disk is discovered by your operating system, you can browse
to the video's (and .jpg pictures if it was set to 'photo'). You will
find them under disk:/DCIM/100MEDIA/ numbered 001, 002, etc. <br/><strong>Do not try
to view the videos directly from the camera, as this will result in poor
quality / choppy video.</strong></li>
			<li>Copy the .avi and .jpg files to a place you can easily find again
(e.g. your desktop) and view them from there.</li>
			<li>Upload the videos to YouTube, or enter it into the [link]<strong>TERENA 25 Year Anniversary Contest</strong>[/link] for the chance to win an iPad!</li>
		</ol>
	</li>
	
	
	</ol>
</p>
