<div id="content">
    	<div class="bigbox">
      <div class="body">
      	<h1>Credits</h1>
        <p>
        	The TERENA Networking Conference 2012 is organised by TERENA, the Trans-European Research and Education Networking Association and hosted by the Icelandic National Research and Education Network (RHnet) and the University of Iceland and held in the picturesque, city of Reykjavik, Iceland from 21 to 24 May 2012.
        </p>

        <table class="tnc" summary="The TNC2011 is hosted by CESNET">
         <thead>
           	<tr>
            	<th colspan="3">Local Host</th>
            </tr>
           </thead>
           <tbody>
          	<tr class="odd">
            	<td>Jón Ingi Einarsson</td>
              <td>RHnet</td>
              <td>Iceland</td>
            </tr>
             </tbody>
        </table>

        <table class="tnc" summary="The conference is organized by Miroslav Milinović, Ji&#345;&iacute; Navr&aacute;til, Bert van Pinxteren, Gyöngyi Horváth">
          <thead>
           	<tr>
            	<th colspan="3">Conference Organisation</th>
            </tr>
           </thead>
          <tbody>
          	<tr class="odd">
              <td>Miroslav Milinović</td>
              <td>SRCE / TERENA</td>
              <td>Croatia</td>
            </tr>
            <tr>
              <td>Jón Ingi Einarsson</td>
              <td>RHnet</td>
              <td>Iceland</td>
            </tr>
             <tr class="odd">
              <td>Ymir Vigfusson</td>
              <td>University of Reykjavik</td>
              <td>Iceland</td>
            </tr>
            <? /*<tr>
              <td></td>
              <td></td>
              <td></td>
            </tr>*/ ?>
            <tr class="odd">
              <td>Bert van Pinxteren</td>
              <td>TERENA</td>
              <td></td>
            </tr>
            <tr>
              <td>Gyöngyi Horváth</td>
              <td>TERENA</td>
              <td></td>
            </tr>
                     </tbody>
        </table>

        <? /* 
        <table class="tnc" summary="Network support for the TNC2012 is provided by Jón Ingi Einarsson from RHnet">
         <thead>
         		<tr>
          		<th colspan="3">Network Support</th>
          	</tr>
         	</thead>
	       <tbody>
          	<tr class="odd">
            	<td></td>
            	<td></td>
            	<td></td>
            </tr>
            <tr>	
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr class="odd">
            <td></td>
            <td></td>
            <td></td>
            </tr>
          </tbody>
        </table>
            */ ?>
       
        <table class="tnc" summary="Local support for the TNC2012">
          <thead>
         		<tr>
          		<th colspan="3">Local Support</th>
          	</tr>
         	</thead>
          <tbody>
          	<tr class="odd">
            	<td><strong>PCO</strong></td>
              <td>PCO</td>
              <td>Iceland</td>
            </tr>
          </tbody>
        </table>
      
        
        </div>
        <div class="closer"></div>
      </div><!--end bigbox-->

      <div class="bigbox">
      	<div class="body">
        <h1>TNC2012 Programme Committee</h1>
        <table class="tnc" summary="TNC2012 programme committee">
          <thead>
          	<tr>
            	<th colspan="3">Chairman</th>
            </tr>
         	</thead>
          <tbody>
          	<tr class="odd">
            <td>David <strong>Kelsey</strong></td>
              <td>STFC Rutherford Appleton Laboratory</td>
              <td>United Kingdom</td>
            </tr>
          </tbody>
        </table>

        <table class="tnc" summary="TNC2012 programme committee">
          <thead>
          	<tr>
            	<th colspan="3">Members</th>
            </tr>
         	</thead>
          <tbody>
          <tr>
            	<td>Bartosz <strong>Belter</strong></td>
              <td>PSNC</td>
              <td>Poland</td>
            </tr>
            
			<tr>
            	<td>John <strong>Chevers</strong></td>
              <td>DANTE</td>
              <td></td>
            </tr>
            
            <tr>
            	<td>Lionel <strong>Ferette</strong></td>
              <td></td>
              <td>Belgium</td>
            </tr>
        
          	 <tr>
            	<td>Ana <strong>Preston Hunsinger</strong></td>
              <td>Internet2</td>
              <td>USA</td>
            </tr>
            
            <tr class="odd">
            	<td>Bartlomiej <strong>Idzikowski</strong></td>
              <td>PSNC</td>
              <td>Poland</td>
            </tr>            
                    
            <tr class="odd">
            	<td>Leif <strong>Johansson</strong></td>
              <td>SUNET</td>
              <td>Sweden</td>
            </tr>
                    
            <tr class="odd">
            	<td>Zenon <strong>Mousmoulas</strong></td>
              <td>GRNET</td>
              <td>Greece</td>
            </tr>
			
			<tr>
            	<td>Ji&#345;&iacute; <strong>Navr&aacute;til</strong></td>
              <td>CESNET</td>
              <td>Czech Republic</td>
            </tr>

            <tr>
            	<td>Brook <strong>Schofield</strong></td>
              <td>TERENA</td>
              <td></td>
            </tr>
            
				<tr class="odd">
            	<td>Niels <strong>van Dijk</strong></td>
              <td>SURFnet</td>
              <td>Netherlands</td>
            </tr>            
            
				<tr class="odd">
            	<td>Ymir <strong>Vigfusson</strong></td>
              <td>University of Reykjavik</td>
              <td>Iceland</td>
            </tr>
           
            <tr>
            	<td>Stefan <strong>Winter</strong></td>
              <td>RESTENA</td>
              <td>Luxembourg</td>
            </tr>
             

      		</tbody>
        </table>

<table class="tnc" summary="TNC2011 TERENA support">
	<thead>
		<tr>
			<th colspan="3">TERENA support</th>
		</tr>
	</thead>
<tbody>
	<tr class="odd">
		<td>Miroslav <strong>Milinović</strong></td>
		<td>TERENA VP Conferences</td>
		<td>Srce, University of Zagreb, Croatia</td>
	</tr>
	<tr class="even">
		<td>Karel <strong>Vietsch</strong></td>

		<td>TERENA</td>
		<td></td>
	</tr>
	<tr class="odd">
		<td>Bert <strong>van Pinxteren</strong></td>
		<td>TERENA</td>
		<td></td>
	</tr>
	<tr class="even">
		<td>Gy&ouml;ngyi <strong>Horv&aacute;th</strong></td>
	  <td>TERENA</td>
	  <td></td>
  	</tr>
	<tr class="odd">
		<td>Christian <strong>Gijtenbeek</strong></td>
		<td>TERENA</td>
		<td>(technical support)</td>
	</tr>
	<tr class="even">
		<td>Dyonisius <strong>Visser</strong></td>
		<td>TERENA</td>
		<td>(technical support)</td>
	</tr>  	
</tbody>
</table>

      	</div>
        <div class="closer"></div>
      </div><!--end bigbox-->
    </div>
    <div id="sidebar">
    	<div class="box">
      	<div class="body">
        	<div class="vcard">
            <h2><span class="fn org">TERENA TNC2012</span></h2>

            <div class="adr">
              <span class="street-address">Singel 468 D</span><br />
              <span class="locality">Amsterdam</span>,
              <span class="postal-code">1017 AW</span>
              <div class="country-name">The Netherlands</div>
            </div>
            <div class="tel">
              <abbr class="type" title="voice">T:</abbr>
              <span class="value">+31 20 530 44 88</span>
            </div>
            <div class="tel">
              <abbr class="type" title="fax">F:</abbr>
              <span class="value">+31 20 530 44 99</span>
            </div>

            <div class="em">Email:
              <span class="email"><a href="mailto:tnc2012@terena.org">tnc2012@terena.org</a></span>
            </div>
            <div>Url:
              <a class="url" href="http://tnc2012.terena.org/">http://tnc2012.terena.org/</a>
            </div>
            <div class="em">Technical Support Email:
              <span class="email"><a href="mailto:help@tnc2012.org">help@tnc2012.org</a></span>
            </div>
          </div><!--end vcard-->
          
          
      	</div><!--end body-->
        <div class="closer"></div>
      </div><!--end box-->
<? /* 
      <div class="box">
      	<div class="body">
          <div class="vcard">
            <h2><span class="fn org">CESNET</span></h2>

            <div class="adr">
              <span class="street-address">Zikova 4</span><br />
              <span class="locality">Prague</span>
              <span class="postal-code">160 00</span>
              <div class="country-name">Czech Republic</div>
            </div>
            <div class="tel">
              <abbr class="type" title="voice">T:</abbr>
              <span class="value">+420 224 355 293</span>
            </div>
                      
            <div class="em">Email:
              <span class="email"><a href="mailto:tnc2011@cesnet.cz">tnc2011@cesnet.cz</a></span>
            </div>
            <div>Url:
              <a class="url" href="http://www.cesnet.cz/">http://www.cesnet.cz/</a>
            </div>
          </div><!--end vcard-->
        </div><!--end body-->
        <div class="closer"></div>
      </div><!--end box-->

      <div class="box">
      <div class="body">
          <div class="vcard">
            <h2><span class="fn org">GUARANT International</span></h2>

            <div class="adr">
              <span class="street-address">Opletalova 22</span><br />
              <span class="locality">Prague 1</span>
              <span class="postal-code">110 00</span>
              <div class="country-name">Czech Republic</div>
            </div>
            <div class="tel">
              <abbr class="type" title="voice">T:</abbr>
              <span class="value">+420 284 001 444</span>
            </div>
            <div class="tel">
              <abbr class="type" title="fax">F:</abbr>
              <span class="value">+420 284 001 448</span>
            </div>

            <div class="em">Email:
              <span class="email"><a href="mailto:terena2011@guarant.cz">terena2011@guarant.cz</a></span>
            </div>
            <div>Url:
              <a class="url" href="http://www.guarant.com/">www.guarant.com</a>
            </div>
          </div><!--end vcard-->
      	</div><!--end body-->
        <div class="closer"></div>
      </div><!--end box-->
     */ ?>
    </div>

    <div class="clearer"></div>

