	      <h1>Welcome to TNC2012</h1>
      <h2>21 - 24 May, Reykjavík, Iceland</h2>

      <p>The TERENA Networking Conference (TNC) is the largest and most prestigious European research networking conference - over 500 participants including decision makers, networking specialists and managers from all major European networking and research organisations, universities, worldwide sister institutions and industry representatives attend.</p>
	  <p>Through keynote speeches by renowned specialists and many parallel sessions, the Conference presents an overview of the latest developments in research networking, both in the technical field and in the areas of application and management.</p>
	  <p>The TNC2012 will be hosted by the Icelandic National Research and Education Network (RHnet) and the University of Iceland and held in the picturesque city of Reykjavik in Iceland from 21-24 May 2012. RHnet provides network connectivity to all state universities and research institutes. With respect to its research activities and accomplishments, RHnet represents Iceland in the development of the Nordic network, NORDUnet, that takes part in the pan-European network GÉANT and participates actively in the project implementation. This sets the perfect scene for TNC2012.</p>
	  
<? /*<h2>Living the network life</h2>
<p>This year's conference theme is "Living the Network Life" and will explore some of the technology and social implications of the emerging network lifestyles. <a href="http://tnc2011.terena.org/participate/" title="Read more...">Read more...</a></p>

    
    <div class="bigbox">
		<div class="body">
	    	<h2>News</h2>
        		<ul class="striped">
          		{foreach item=item key=key from=$news}
          		<li class="{cycle values="odd,even"}">
          		<a href="/media/news.php?news_id={$item.news_id}">{$item.headline}</a>
          		</li>
          		{/foreach}
          	</ul>
      	</div><!--end bigbox body-->

		<div class="closer"></div>
	</div><!--end bigbox-->
	*/ ?>
	<div class="bigbox">
		<div class="body">
	    	<h2>Past TERENA Networking Conferences</h2>
        		<table class="img_grid">
        		<tbody>
        		<tr>
				<td><strong><a href="https://tnc2011.terena.org/">TNC2011</a></strong></td>
        		<td><strong><a href="https://tnc2010.terena.org/">TNC2010</a></strong></td>
        		<td><strong><a href="https://tnc2009.terena.org/">TNC2009</a></strong></td>
        		<td><strong><a href="https://tnc2008.terena.org/">TNC2008</a></strong></td>
        		<td><strong><a href="http://www.terena.org/events/past.php">earlier...</a></strong></td>
      </tr></tbody></table>
      	</div><!--end bigbox body-->

		<div class="closer"></div>
	</div><!--end bigbox-->

	      <div class="bigbox">
		<div class="body">

			<h2>Sponsors TNC2012</h2>

			<table class="img_grid">
				<tbody>
						<tr>
							<td><a href="/webdemo/sponsors/#template"><img alt="template" src="/includes/tnc2011/gfx/sponsor-template-small.jpg" /></a></td>
						</tr>
				</tbody>
			</table>


			
	    	<h2>Sponsors TNC2011</h2>

			<table class="img_grid">
				<tbody>
					<tr>
						<td><a href="/webdemo/sponsors/#nsn"><img alt="nsn" src="/includes/tnc2011/gfx/logos/nsn_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#cisco"><img alt="cisco" src="/includes/tnc2011/gfx/logos/cisco_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#huawei"><img alt="huawei" src="/includes/tnc2011/gfx/logos/huawei_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#advaoptical"> <img alt="adva optical networking" src="/includes/tnc2011/gfx/logos/adva_small.gif" /></a></td>
						<td><a href="/webdemo/sponsors/#vidyo"><img alt="vidyo" src="/includes/tnc2011/gfx/logos/vidyo_small.gif" /></a></td>
					</tr>

					<tr>
						<td><a href="/webdemo/sponsors/#customconnect"><img alt="Custom Connect" src="/includes/tnc2011/gfx/logos/custom_connect_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#ripe"><img alt="ripe" src="/includes/tnc2011/gfx/logos/ripe_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#juniper"><img alt="juniper" src="/includes/tnc2011/gfx/logos/juniper_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#comodo"><img alt="comodo" src="/includes/tnc2011/gfx/logos/comodo_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#extreme"><img alt="extreme networks" src="/includes/tnc2011/gfx/logos/extreme_small.gif" /></a></td>
					</tr>

					<tr>
						<td><a href="/webdemo/sponsors/#level3"><img alt="level3" src="/includes/tnc2011/gfx/logos/level3_small.gif" /></a></td>
						<td><a href="/webdemo/sponsors/#cesnet"><img alt="cesnet" src="/includes/tnc2011/gfx/logos/cesnet_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/europeancommission"><img alt="european commission" src="/includes/tnc2011/gfx/logos/ecflag_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/europeancommission"><img alt="european commission" src="/includes/tnc2011/gfx/logos/FP7_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#av"><img alt="av" src="/includes/tnc2011/gfx/logos/av_small.jpg" /></a></td>
					</tr>

					<tr>
						<td><a href="/webdemo/sponsors/#ics"><img alt="ics" src="/includes/tnc2011/gfx/logos/ics_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#ctu"><img alt="ctu" src="/includes/tnc2011/gfx/logos/ctu_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#ciena"><img alt="ciena" src="/includes/tnc2011/gfx/logos/ciena_small.gif" /></a></td>
						<td><a href="/webdemo/sponsors/#accessict"><img alt="accessict" src="/includes/tnc2011/gfx/logos/accessict_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#inveatech"><img alt="inveatech" src="/includes/tnc2011/gfx/logos/inveatech_small.jpg" /></a></td>
					</tr>

					<tr>
						<td><a href="/webdemo/sponsors/#infinera"><img alt="infinera" src="/includes/tnc2011/gfx/logos/infinera_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#msmt"><img alt="msmt" src="/includes/tnc2011/gfx/logos/msmt_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#mashable"><img alt="mashable" src="/includes/tnc2011/gfx/logos/mashable_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#idg"><img alt="idg" src="/includes/tnc2011/gfx/logos/idg_small.jpg" /></a></td>
						<td><a href="/webdemo/sponsors/#cw"><img alt="cw" src="/includes/tnc2011/gfx/logos/cw_small.jpg" /></a></td>
					</tr>
				</tbody>
			</table>


       	</div><!--end bigbox body-->
	  	<div class="closer"></div>
    </div><!--end bigbox-->
    </div><!--end content-->

    <div id="sidebar">


	  	<div class="box">
				<div class="body">
					<h1>Sponsorship opportunities</h1>
					Please contact <a href="mailto:horvath@terena.org?subject=TNC2012" title="Contact Gyöngyi Horváth">Gyöngyi Horváth</a> and read the brochure:<br />
					<a href="/includes/tnc2011/documents/sponsorbrochure.pdf">
		 	<img alt="tnc2012 sponsor" src="/includes/tnc2011/gfx/sponsorbrochure.jpg" />
		 	</a>
				</div>
      	<div class="closer"></div>
	  	</div><!--end box-->

<? /*
		<div class="box">
				<div class="body">
					<a href="/webdemo/participate/register"><h1>TNC2011 <br />On site registration</h1></a>
				</div>
      	<div class="closer"></div>
	  	</div><!--end box-->
	  	*/ ?>
  	<? /* <div class="box">
      	<div class="body">
		<?= $this->render('_shared/terena_vcard.phtml'); ?>
        </div><!--end box body-->
        <div class="closer"></div>
    	</div><!--end box-->

  	<div class="box">
				<div class="body promo">
					<h1>TNC 2011 Promo</h1>
					<span><a href="/media/promo.php">Promotional Video TNC2011</a></span>
				</div>
      	<div class="closer"></div>
	  	</div><!--end box-->*/ ?>
	  <? /*
  	<div class="box">
			<div class="body">
				<h1>TNC 2011 Promo</h1>
				<a class="sns-join">Join our Facebook group</a>
			</div>
    	<div class="closer"></div>
		</div><!--end box-->
		*/ ?>

 <!--content div-->
