	  
	  <div class="bigbox">
		<div class="body">
	<h1>CALL FOR PAPERS</h1>	
	<h3>Guidelines for paper (abstract) submission</h3>
	      
      <? /*<p>To submit your paper (extended abstract), please place it in the drop box at: <a href="http://tnc2012.terena.org/participate/submit">http://tnc2012.terena.org/participate/submit</a></p>*/ ?>
      <p>
      Extended abstracts are invited on all subjects relevant to the spirit and objectives of the conference: to present, discuss and learn about the latest developments in networking technology for the research and education community and their use by the community. The suggested conference topics are an indication of the planned scope of the conference, but are not meant to be restrictive.
      </p>
      <p>
      Extended abstracts of 600 to 1200 words (one to two A4 pages) must be submitted in English, the official language of the conference. These should be accompanied (attached to the extended abstract above the two pages) by a short professional biography of the author(s) and the full names and contact details of the author(s) as outlined below.  Keywords will assist the programme committee in planning the final programme of the conference.
      </p>
      <p>
      The Conference Programme Committee will review all abstracts submitted to the conference on the basis of a set of criteria including the quality of the submission and its relevance to this conference, originality and international scope of the subject matter.
      </p>

      <h2>Format</h2>
      <p>Extended abstracts should be submitted in HTML, PDF, Word, Open Office or as plain ASCII text files.</p>
      
      <h1>Guidelines for full paper submission</h1>
      <i>(Accepted papers only)</i>
      <p>Full paper format should be submitted (by uploading it to the speaker's page or via e-mail to <a href="mailto:horvath@terena.org">horvath@terena.org</a>) following the <strong><a href="/includes/tnc2011/documents/20101006_tnc2011_guidelines_fullpapers.doc" title="guidelines">guidelines</a></strong> and completing the <strong><a href="/includes/tnc2011/documents/20101006_tnc2011_jar_form.pdf" title="jarform">JAR form</a></strong>.</p>

      <h2>Structure</h2>
      <p>All abstracts should be structured in the following order: Title, Authors, Author Affiliations, Keywords, Abstract, Acknowledgements, References, Author Biographies.</p>

      <h2>Authors and Author Affiliation(s)</h2>
      <p>The first and family names of all authors and co-authors should be provided. The organisational affiliation, postal address and e-mail address of each author should also be listed.</p>

      <h2>Keywords</h2>
      <p>Abstracts should include between one and five keywords to describe the contents. Each keyword (which may be a phrase or a single word) should describe a single concept. Conjunctives (words such as "and", and "while" which join words or, phrases together) and common words such as "computer" should be avoided. Abbreviations and acronyms should be spelt out (e.g. "Asynchronous Transfer Mode" instead of "ATM") unless the abbreviation is so well established that the full term is rarely used, for example, use "laser" instead of "Light Amplification by Stimulated Emission of Radiation".</p>

      <h2>Authors Biographies</h2>
      <p>Short biographies (maximum of 100 words) should be provided for each author of the paper. Biographies should be included at the end of the paper under the heading "Vitae".</p>

      <h2>Notification of Acceptance</h2>
      <p>Notification of acceptance will be sent to authors by 23 January 2012.</p>
		</div><!--end body-->
    <div class="closer"></div>
	</div><!--end bigbox-->
	
		<div class="bigbox">
  	<div class="body">
      <h1>CALL FOR SPONSORED STUDENT POSTER PLACES</h1>
      <? /*<i>Sponsored by Cisco Systems</i>*/ ?>
      <p>Students can apply to attend the conference free of charge: a limited number of sponsored registration places will be available for bona fide postgraduate students from relevant fields.<br />
Call for Student contribution will be announced in January 2011, follow the news and announcements.</p>
      
	<? /*<p>There is limited number of sponsored registration places for bona-fide students from relevant fields. Eligible students will receive free admission to the conference and are expected to present a poster at the conference and online. The best student poster will receive an award at the end of the conference.</p><p>To apply, students are encouraged to submit a short poster abstract (100 to 250 words) on any of the subjects relevant to the spirit and objectives of the conference. Applications should be sent to <a href="mailto:tnc2011@terena.org">tnc2011@terena.org</a> with the subject &lsquo;TNC 2011 Student Poster&lsquo; by <br /><strong>30 April 2011</strong>.</p>
	<p>A subpanel of the Program Committee will select the best papers for acceptance and inform all submitting students before the end of the early registration.</p>*/ ?>
	<h2>CALL FOR POSTERS</h2>

<p>In the last two years, several TNC participants have created <a href="https://tnc2011.terena.org/core/poster/list">high quality poster presentations</a>. An effective poster presentation is not just a standard research paper stuck to a board. It should summarise your work with graphs and images to tell the story and should use text more sparingly. Featuring a poster at TNC will serve as an excellent advertisement for your work, and can act as a great conversation starter with TNC participants.

In general, poster presentations are less formal than regular presentations, are more interactive and can provoke various points of view. Selected posters will be displayed in an area close to the parallel sessions and on the conference website. Applications should be sent to <a href="mailto:tnc2012@terena.org?subject=TNC2012%20Poster">tnc2012@terena.org</a> with the subject "TNC2012 Poster" by 30 April 2011.</p>

<h2>GIVE A LIGHTNING TALK</h2>
<div>
<p>Lightning talks are five-minute presentations focusing on one key point; this can be an idea, a successful project, a cautionary story, a collaboration invitation, a quick tip or a demonstration.<br />

Use this time wisely to present the pertinent message of the subject matter without the need for background history, the problem space or a business-case justification.<br />

Lightning talks are an excellent opportunity for first-time speakers.<br />

We will have sixteen lightning talks at TNC2012.<br />
Email <a href="mailto:lightning-talks@terena.org?subject=TNC2012%20Lightning%20Talk">lightning-talks@terena.org</a> including your bio, a proposed title and a short description of your talk. The deadline for submissions is 18 April 2012.</p>
</div>
	  </div><!--end bigbox body-->

        <div class="closer"></div>
      </div><!--end bigbox-->
	
</div><!--end content-->

<div id="sidebar">
	<div class="box">
  	<div class="body">
  	<h1>Important Dates</h1>
    	<table class="tnc" summary="important dates for the TERENA Networking Conference 2012">
          <tr class="odd">
            <td>Extended abstracts</td>
            <td><strong>30 November 2011</strong></td>
	          </tr>
          <tr>
            <td>Notification of acceptance</td>
            <td>23 January 2012</td>
          </tr>
          <tr class="odd">
          	<td>Registration commences:</td><td>20 February 2012</td>
          </tr>
          <tr>
          	<td>Submission of full papers:</td><td>16 April 2012</td>
          </tr>
          <tr class="odd">
          	<td>Submission of posters:</td><td>30 April 2012</td>
          </tr>
          <tr class="odd">
          	<td>Submission of poster pdf:</td><td>6 May 2012</td>
          </tr>
          <tr>
          	<td>Presentation slides<sup><strong>*</strong></sup>:</td><td>1 May 2012</td>
          </tr>
          <tr class="odd">
          	<td>Conference:</td><td>21 - 24 May 2012</td>
          </tr>
      </table>
      <p>* Please note that presentation slides may be updated by the speaker up to 30 minutes before the presentation.</p>
      
      
         
    </div><!--end body-->
    
    
    
    <div class="closer"></div>
   </div><!--end box -->
   