<?
/*
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination

The url view helper can use a custom route. In order to do that you have to set the parameter route_name to the name of the route
eg. $this->paginationControl($this->presentations, 'Sliding', '_paginator.phtml', array('route_name' => 'presentations'));
*/
?>

<? if ($this->pageCount): ?>
<div class="pagination_control">
<!-- Previous page link -->
<? if (isset($this->previous)): ?>
  <a href="<? echo $this->url(array('page' => $this->previous), $this->route_name); ?>">
    &lt; Previous
  </a> |
<? else: ?>
  <span class="disabled">&lt; Previous</span> |
<? endif; ?>

<!-- Numbered page links -->
<? foreach ($this->pagesInRange as $page): ?>
  <? if ($page != $this->current): ?>
    <a href="<? echo $this->url(array('page' => $page), $this->route_name); ?>">
        <? echo $page; ?>
    </a> |
  <? else: ?>
    <? echo $page; ?> |
  <? endif; ?>
<? endforeach; ?>

<!-- Next page link -->
<? if (isset($this->next)): ?>
  <a href="<? echo $this->url(array('page' => $this->next), $this->route_name); ?>">
    Next &gt;
  </a>
<? else: ?>
  <span class="disabled">Next &gt;</span>
<? endif; ?>
</div>
<? endif; ?>

