<h1>Conferences</h1>
<? if ($this->authInfo()->isAdmin() ): ?>
<div class="actions"><a href="/core/conference/new" title="Add new conference">add</a></div>
<? endif;

// filter out hidden columns
function globFilter($input)
{
	return !isset($input['hidden']);
}
$columns = array_filter($this->grid['cols'], 'globFilter');
?>
<? if ($this->grid['rows']->count() !== 0): ?>
<? if ( ($this->grid['rows'] instanceof Zend_Paginator) && ($this->grid['rows']->getTotalItemCount() > $this->grid['rows']->getItemCountPerPage()) ): ?>
<?= $this->paginationControl($this->grid['rows'], 'Sliding', '_paginator.phtml', array('route_name' => 'grid')); ?>
<? endif; ?>
<table class="grid" cellspacing="0">
<thead>
<tr>
<? foreach (array_keys($columns) as $col):  ?>
<? $dir = ($this->grid['params']['dir'] === 'desc') ? 'asc' : 'desc' ?>
<th>
	<? if ($columns[$col]['sortable'] === true): ?>
	<a href="<?= $this->url(array('order' => $col, 'dir' => $dir), 'grid') ?>"><?= $columns[$col]['label'] ?></a>
	<? else: ?>
	<?= $columns[$col]['label'] ?>
	<? endif; ?>
	<? if ($columns[$col]['field'] === $this->grid['params']['order']): ?>
	<img class="" src="/includes/core/gfx/icons/sort_<?=$dir?>.gif" alt="sort icon" />
	<? endif; ?>
</th>
<? endforeach; ?>
<th>Actions</th>
</tr>
</thead>
<tbody>
<? foreach ($this->grid['rows'] as $item): ?>
  <tr class="<?= $this->cycle(array('odd', 'even'))->next() ?>">
  	<? foreach (array_keys($columns) as $col):  ?>
  		<td>  		
  		<?
  		// apply modifiers
  		// @todo: migrate this Closure testing to _grid.phtml
  		if ( isset($columns[$col]['modifier']) ) {
  			if ($columns[$col]['modifier'] instanceof Closure) {
				echo $columns[$col]['modifier']($item->$col);
  			} else {
  				echo call_user_func(array($this, $columns[$col]['modifier']), $item->$col);
  			}
  		} else {
  			if ($col == 'name') {
  				echo '<a href="http://'.$item->hostname.'" title="visit conference website">'.$item->$col.'</a>';
  			} else {
  				echo $item->$col;
  			}
  		}
  		?>
  		</td>
  	<? endforeach; ?>
	<td>
		<a href="<?= $this->url(array('controller' => 'conference', 'action' => 'edit', 'id' => $item->{$this->grid['primary']}), 'gridactions') ?>">edit</a>
		| <a href="<?= $this->url(array('controller' => 'conference', 'action' => 'timeslots', 'id' => $item->{$this->grid['primary']}), 'gridactions') ?>">timeslots</a>
	</td>
  </tr>
<? endforeach; ?>
</tbody>
</table>
<? endif; ?>
<? if ( ($this->grid['rows'] instanceof Zend_Paginator) && ($this->grid['rows']->getTotalItemCount() > $this->grid['rows']->getItemCountPerPage()) ): ?>
<?= $this->paginationControl($this->grid['rows'], 'Sliding', '_paginator.phtml', array('route_name' => 'grid')); ?>
<? endif; ?>