<h1>Edit account</h1>
<? if ($this->authInfo()->isAdmin()): ?>
<a href="<?= $this->url(array('action'=>'roles', 'id'=>$this->id), 'main-module') ?>">roles</a>
<? endif; ?>
<?= $this->userForm ?>

<? if ($myPresentations = Zend_Auth::getInstance()->getIdentity()->getMyPresentations()):
$presModel = new Core_Model_Presentation();
$filter = new stdClass();
$filter->filters = new stdClass();
$filter->filters->presentation_id = $myPresentations;
$presentations = $presModel->getPresentations(null, array('presentation_title', 'asc'), $filter, true);
?>
<? if ($presentations): ?>
<h2>My presentatio<?= (count($presentations['rows']) == 1) ? 'n': 'ns' ?></h2>
<ul class="titles">
<? foreach ($presentations['rows'] as $presentation): ?>
<li><a href="<?= $this->url(array('controller' => 'presentation', 'action' => 'show', 'id' => $presentation['presentation_id']), 'oneitem') ?>" title="edit presentation">
<?= $presentation['presentation_title'] ?></a>
</li>
<? endforeach; ?>
</ul>
<? endif; ?>
<? endif; ?>

<?
if ($mySubmits = Zend_Auth::getInstance()->getIdentity()->getMySubmissions()):
$submitModel = new Core_Model_Submit();
$filter = new stdClass();
$filter->filters = new stdClass();
$filter->filters->submission_id = $mySubmits;
$submits = $submitModel->getSubmissions(null, array('date', 'desc'), $filter);
?>
<br />

<h2>My Submitted papers</h2>
<ul>
<? foreach ($submits['rows'] as $submit): ?>
<li><a href="<?= $this->url(array('controller' => 'submit', 'action' => 'edit', 'id' => $submit->submission_id)) ?>" title="edit submission">
<?= $submit->title ?></a>
(<?= $this->formatDate($submit->date) ?>)
</li>
<? endforeach; ?>
</ul>
<? endif; ?>