<table summary="Photo impressions of Iceland" class="photos">
  <tbody>
  <tr>
  <td><a href="/includes/tnc2011/gfx/photos/venue/1.jpg" rel="lightbox[Iceland]"><img alt="Iceland" src="/includes/tnc2011/gfx/photos/venue/1_small.jpg" /></a></td>
  <td><a href="/includes/tnc2011/gfx/photos/venue/2.jpg" rel="lightbox[Iceland]"><img alt="Iceland" src="/includes/tnc2011/gfx/photos/venue/2_small.jpg" /></a></td>
  <td><a href="/includes/tnc2011/gfx/photos/venue/3.jpg" rel="lightbox[Iceland]"><img alt="Iceland" src="/includes/tnc2011/gfx/photos/venue/3_small.jpg" /></a></td>
	</tr>
  <tr>
  <td><a href="/includes/tnc2011/gfx/photos/venue/4.jpg" rel="lightbox[Iceland]"><img alt="Iceland" src="/includes/tnc2011/gfx/photos/venue/4_small.jpg" /></a></td>
  <td><a href="/includes/tnc2011/gfx/photos/venue/5.jpg" rel="lightbox[Iceland]"><img alt="Iceland" src="/includes/tnc2011/gfx/photos/venue/5_small.jpg" /></a></td>
  <td><a href="/includes/tnc2011/gfx/photos/venue/6.jpg" rel="lightbox[Iceland]"><img alt="Iceland" src="/includes/tnc2011/gfx/photos/venue/6_small.jpg" /></a></td>
	</tr>
  <tr>
  <td><a href="/includes/tnc2011/gfx/photos/venue/7.jpg" rel="lightbox[Iceland]"><img alt="Iceland" src="/includes/tnc2011/gfx/photos/venue/7_small.jpg" /></a></td>
  <td><a href="/includes/tnc2011/gfx/photos/venue/8.jpg" rel="lightbox[Iceland]"><img alt="Iceland" src="/includes/tnc2011/gfx/photos/venue/8_small.jpg" /></a></td>
  <td><a href="/includes/tnc2011/gfx/photos/venue/9.jpg" rel="lightbox[Iceland]"><img alt="Iceland" src="/includes/tnc2011/gfx/photos/venue/9_small.jpg" /></a></td>
	</tr>
	<tr>
	<td><a href="/includes/tnc2011/gfx/photos/venue/11.jpg" rel="lightbox[Iceland]"><img alt="Iceland" src="/includes/tnc2011/gfx/photos/venue/11_small.jpg" /></a></td>
	<td><a href="/includes/tnc2011/gfx/photos/venue/12.jpg" rel="lightbox[Iceland]"><img alt="Iceland" src="/includes/tnc2011/gfx/photos/venue/12_small.jpg" /></a></td>
	<td><a href="/includes/tnc2011/gfx/photos/venue/10.jpg" rel="lightbox[Iceland]"><img alt="Iceland" src="/includes/tnc2011/gfx/photos/venue/10_small.jpg" /></a></td>
	</tr>          	
  </tbody>
</table>